// js/prompts.js
// FONTE DE DADOS CENTRAL PARA O CONTEÚDO DAS AULAS

const lessonData = {
    a1: {
        titles: [
            "", "Hello, World!", "Where Are You From?", "My World", "The Alphabet & Numbers",
            "Contact Information", "Everyday Objects", "This or That?", "Review (Module 1)",
            "My Daily Routine", "His/Her Routine", "Do You Like Music?", "I Don't Like That",
            "Object Pronouns", "How Often?", "What Time Is It?", "Review (Module 2)",
            "Possessive 's", "My Job", "My House", "Where Is the Bank?", "How much / many?",
            "A little / a few", "Can / Can't", "What Are You Doing?", "Simple Present vs. Continuous",
            "Review (Module 3)", "Where Were You Born?", "What Did You Do Yesterday?",
            "Questions in the Past", "Future Plans", "Final Review", "Final Project"
        ],
        prompts: { // Prompts de REVISÃO (aula concluída)
            1: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é cumprimentar e perguntar o nome. Siga estes passos:\n1. Inicie um diálogo simples comigo, como se estivéssemos numa festa. Comece com "Hello!".\n2. Espere pela minha resposta.\n3. Pergunte o meu nome usando "What's your name?".\n4. Quando eu responder, diga "Nice to meet you!".`,
            2: `Estou aprendendo inglês.\nAja como um agente de imigração. O tópico é perguntar a nacionalidade. Siga estes passos:\n1. Cumprimente-me e faça a pergunta "Where are you from?".\n2. Espere pela minha resposta.\n3. Depois, faça mais duas perguntas sobre a minha origem (ex: "What city?").\n4. No final, diga "Welcome and enjoy your stay!".`,
            3: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é apresentar pessoas. Siga estes passos:\n1. Explique brevemente como usar "This is my..." para apresentar alguém.\n2. Dê um exemplo: "This is my brother. His name is John.".\n3. Peça-me para eu apresentar duas pessoas da minha família (mãe e pai).\n4. Espere pela minha resposta e corrija-me se for necessário.`,
            4: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o alfabeto e os números. Siga estes passos:\n1. Diga-me uma palavra simples em inglês (ex: "BOOK").\n2. Peça-me para soletrá-la ("Can you spell that, please?").\n3. Espere pela minha resposta e corrija-a.\n4. Depois, diga um número de telefone (dígito por dígito) e peça-me para o escrever.\n5. Verifique se a minha resposta está correta.`,
            5: `Estou aprendendo inglês.\nAja como rececionista de um hotel. O tópico é pedir informações de contacto. Siga estes passos:\n1. Cumprimente-me e diga que precisa dos meus dados para o check-in.\n2. Peça o meu nome completo, número de telefone e endereço de e-mail, uma pergunta de cada vez.\n3. Espere pelas minhas respostas.\n4. No final, agradeça e confirme as informações.`,
            6: `Estou aprendendo inglês.\nAja como o meu professor de inglês. O tópico são os objetos do dia a dia. Siga estes passos:\n1. Mostre-me (descreva) 3 objetos virtuais diferentes (ex: a pen, an eraser, a book).\n2. Para cada objeto, pergunte "What's this?".\n3. Espere pela minha resposta ("It's a/an...").\n4. Corrija-me se eu errar o artigo 'a' ou 'an'.`,
            7: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são os pronomes demonstrativos. Siga estes passos:\n1. Explique em 2 frases a diferença entre 'this'/'that' e 'these'/'those'.\n2. Crie um exercício com 2 frases para eu completar com o pronome correto.\n3. Espere pela minha resposta e corrija-a.`,
            8: `Estou aprendendo inglês.\nAja como um novo colega de trabalho. O tópico é uma revisão geral do módulo 1. Siga estes passos:\n1. Inicie um diálogo, apresente-se e pergunte o meu nome.\n2. Depois de eu responder, pergunte de onde eu sou.\n3. Por fim, peça para eu soletrar o meu apelido.`,
            9: `Estou aprendendo inglês.\nAja como um entrevistador de um podcast. O tópico é a rotina diária (Simple Present). Siga estes passos:\n1. Comece a entrevista e faça-me 3 perguntas sobre a minha rotina, usando "Do you...?" (ex: "Do you wake up early?").\n2. Espere pelas minhas respostas a cada pergunta.\n3. No final, agradeça pela minha participação.`,
            10: `Estou aprendendo inglês.\nAja como o meu editor. O tópico é a 3ª pessoa do singular (he/she/it). Siga estes passos:\n1. Dê-me um pequeno texto (3 frases) sobre a rotina de alguém, mas com erros nos verbos (ex: "He go to work").\n2. Peça-me para encontrar e corrigir os 3 erros.\n3. Espere pela minha resposta e confirme se as correções estão certas.`,
            11: `Estou aprendendo inglês.\nAja como um amigo que está a planear uma festa. O tópico é gostar e não gostar. Siga estes passos:\n1. Pergunte-me sobre 3 géneros musicais usando "Do you like...?" para decidir a playlist da festa.\n2. Espere pelas minhas respostas.\n3. Com base nas minhas respostas, sugira um cantor ou banda.`,
            12: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o negativo 'don't'. Siga estes passos:\n1. Dê-me uma lista de 3 atividades (ex: study math, watch horror movies, eat fish).\n2. Peça-me para criar 3 frases sobre mim, usando "I like..." ou "I don't like...".\n3. Espere pela minha resposta e verifique a estrutura das minhas frases negativas.`,
            13: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são os pronomes objeto (me, him, her, us, them). Siga estes passos:\n1. Dê-me uma frase, como "I need to talk to John.".\n2. Peça-me para reescrever a frase usando um pronome objeto.\n3. Espere pela minha resposta ("I need to talk to him.") e corrija-a.\n4. Repita o processo mais 2 vezes com pessoas diferentes.`,
            14: `Estou aprendendo inglês.\nAja como um médico. O tópico são os advérbios de frequência. Siga estes passos:\n1. Pergunte-me sobre a frequência de 3 hábitos saudáveis usando "How often do you...?" (ex: eat vegetables).\n2. Espere pelas minhas respostas (com 'always', 'sometimes', 'never').\n3. No final, dê-me uma recomendação de saúde com base nas minhas respostas.`,
            15: `Estou aprendendo inglês.\nAja como o meu assistente pessoal. O tópico é dizer as horas. Siga estes passos:\n1. Diga-me 3 compromissos que eu tenho hoje, cada um com um horário diferente (ex: "You have a meeting at half past ten.").\n2. Peça-me para confirmar os horários, escrevendo-os em formato digital (ex: 10:30).\n3. Verifique se as minhas respostas estão corretas.`,
            16: `Estou aprendendo inglês.\nAja como um amigo. O tópico é uma revisão geral do módulo 2. Siga estes passos:\n1. Faça-me uma pergunta sobre os meus gostos ("Do you like...?").\n2. Faça-me uma pergunta sobre a minha rotina ("What time do you usually...?").\n3. Faça-me uma pergunta sobre a frequência de uma atividade ("How often do you...?").\n4. Mantenha um diálogo curto com base nas minhas respostas.`,
            17: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o possessivo 's. Siga estes passos:\n1. Dê-me 3 frases com erros, como 'The car of my sister is red'.\n2. Peça-me para corrigi-las para 'My sister's car is red'.\n3. Espere pela minha resposta e dê feedback sobre as correções.`,
            18: `Estou aprendendo inglês.\nAja como um recrutador. O tópico é falar sobre profissões. Siga estes passos:\n1. Comece uma pequena entrevista e pergunte-me 'What do you do?'.\n2. Deixe-me descrever a minha profissão (ou uma profissão que eu queira).\n3. Faça uma pergunta de seguimento sobre o meu trabalho (ex: 'What do you like about your job?').`,
            19: `Estou aprendendo inglês.\nAja como um agente imobiliário. O tópico é descrever lugares com 'There is/are'. Siga estes passos:\n1. Descreva uma cozinha para mim usando 'There is a...' e 'There are some...'.\n2. Peça-me para descrever o meu quarto usando as mesmas estruturas.\n3. Espere pela minha resposta e corrija se necessário.`,
            20: `Estou aprendendo inglês.\nAja como um turista perdido. O tópico são as preposições de lugar. Siga estes passos:\n1. Peça-me direções para o café mais próximo.\n2. Eu vou tentar explicar usando 'next to', 'opposite', 'between'.\n3. Faça uma pergunta para confirmar se entendeu (ex: 'So, it's next to the bank?').`,
            21: `Estou aprendendo inglês.\nAja como o meu colega de casa. O tópico é 'How much' vs 'How many'. Siga estes passos:\n1. Diga que precisamos de ir às compras.\n2. Faça-me 2 perguntas com 'How many' (ex: eggs) e 2 perguntas com 'How much' (ex: milk).\n3. Espere pelas minhas respostas para criar a nossa lista de compras.`,
            22: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é 'a little' vs 'a few'. Siga estes passos:\n1. Explique em uma frase a diferença entre 'a little' (incontáveis) e 'a few' (contáveis).\n2. Dê-me 2 frases para eu completar com a opção correta.\n3. Espere pela minha resposta e corrija-a.`,
            23: `Estou aprendendo inglês.\nAja como meu amigo. O tópico é o uso de 'can'/'can't'. Siga estes passos:\n1. Pergunte-me sobre 2 habilidades usando 'Can you...?' (ex: 'Can you play the guitar?').\n2. Depois, faça-me um pedido usando 'Can you...?' (ex: 'Can you help me with this box?').`,
            24: `Estou aprendendo inglês.\nAja como se estivéssemos ao telefone. O tópico é o Present Continuous. Siga estes passos:\n1. Cumprimente-me e pergunte 'What are you doing?'.\n2. Deixe-me responder.\n3. Faça mais uma pergunta sobre o que está a acontecer à minha volta (ex: 'Is anyone else there with you?').`,
            25: `Estou aprendendo inglês.\nAja como um jornalista. O tópico é a diferença entre Simple Present e Present Continuous. Siga estes passos:\n1. Pergunte-me: 'What do you usually do on weekends?' (rotina).\n2. Depois de eu responder, pergunte: 'And what are you doing right now?' (ação no momento).\n3. Compare as minhas duas respostas para reforçar a diferença.`,
            26: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é uma revisão do módulo 3. Siga estes passos:\n1. Dê-me um exercício com 3 frases onde eu tenho que escolher entre o Simple Present e o Present Continuous.\n2. Espere pela minha resposta e dê feedback.\n3. Pergunte-me o que eu faria com 'a few' dólares.`,
            27: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o verbo 'to be' no passado (was/were). Siga estes passos:\n1. Dê-me 3 frases com erros em 'was' ou 'were' (ex: 'They was happy.').\n2. Peça-me para encontrar e corrigir os erros.\n3. Espere pela minha resposta e confirme as correções.`,
            28: `Estou aprendendo inglês.\nAja como um amigo curioso. O tópico é o Simple Past. Siga estes passos:\n1. Pergunte-me 'What did you do yesterday?'.\n2. Eu vou responder com 2 ou 3 ações.\n3. Faça uma pergunta de seguimento sobre uma das minhas ações (ex: 'Oh, you watched a movie? Was it good?').`,
            29: `Estou aprendendo inglês.\nAja como um detetive. O tópico são perguntas no passado com 'Did'. Siga estes passos:\n1. Diga que está a investigar um 'crime' (ex: o último biscoito que desapareceu).\n2. Faça-me 3 perguntas sobre onde eu estava e o que fiz ontem, usando 'Did you...?'.\n3. Eu só posso responder 'Yes, I did' ou 'No, I didn't'.`,
            30: `Estou aprendendo inglês.\nAja como um agente de viagens. O tópico são planos futuros com 'going to'. Siga estes passos:\n1. Diga que eu ganhei uma viagem.\n2. Faça-me 3 perguntas sobre os meus planos usando 'Are you going to...?' (ex: 'Are you going to travel alone?').\n3. Com base nas minhas respostas, sugira um destino.`,
            31: `Estou aprendendo inglês.\nAja como um biógrafo. O tópico é uma revisão final do A1. Siga estes passos:\n1. Peça para eu me apresentar (presente).\n2. Pergunte sobre uma memória importante da minha infância (passado).\n3. Pergunte sobre um grande plano que tenho para o próximo ano (futuro).`,
            32: `Estou aprendendo inglês.\nAja como um escritor parceiro. O tópico é praticar a narração de histórias. Siga estes passos:\n1. Comece uma história com a frase: "Last year, I decided to learn a new skill...".\n2. Peça-me para continuar a história, explicando qual foi a habilidade e o que aconteceu.\n3. Adicione mais uma frase à minha história e peça para eu continuar novamente.`
        },
        preview_prompts: { // Prompts de PREPARAÇÃO (próxima aula)
            1: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. Vou ter a minha primeira aula. Siga estes passos:\n1. Ensine-me as 3 formas mais comuns de dizer "olá".\n2. Ensine-me a perguntar "Qual é o seu nome?" e a responder "O meu nome é...".\n3. Crie um mini-diálogo para eu completar, praticando o que aprendi.\n4. Espere pela minha resposta e corrija-a.`,
            2: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico será nacionalidades. Siga estes passos:\n1. Explique como se pergunta "De onde você é?" em inglês.\n2. Dê-me 3 exemplos de países com as suas nacionalidades (ex: Brazil - Brazilian).\n3. Crie um exercício onde me dá um país e eu tenho de dizer a nacionalidade.\n4. Espere pela minha resposta e corrija-a.`,
            3: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico será apresentar pessoas. Siga estes passos:\n1. Explique a diferença entre "his" (para homens) e "her" (para mulheres).\n2. Dê um exemplo: "This is my friend. His name is Paulo. This is my sister. Her name is Ana.".\n3. Crie um exercício para eu completar com "his" ou "her".\n4. Espere pela minha resposta e corrija-a.`,
            4: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico será o alfabeto e os números de 1 a 20. Siga estes passos:\n1. Mostre-me o alfabeto em inglês.\n2. Mostre-me os números de 1 a 20 por extenso.\n3. Faça-me um pequeno teste: diga um número e peça-me para o escrever por extenso.\n4. Espere pela minha resposta e corrija-a.`,
            5: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico será informações de contacto. Siga estes passos:\n1. Ensine-me a perguntar "What's your phone number?" e "What's your email address?".\n2. Explique como dizer "." (dot) e "@" (at) em inglês.\n3. Peça-me para praticar, perguntando-me o meu e-mail.\n4. Espere pela minha resposta e corrija-a.`,
            6: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico serão os artigos 'a' e 'an'. Siga estes passos:\n1. Explique a regra: quando usamos 'a' (antes de som de consoante) e quando usamos 'an' (antes de som de vogal).\n2. Dê-me 3 exemplos de cada.\n3. Crie um exercício com 3 palavras para eu completar com 'a' ou 'an'.\n4. Espere pela minha resposta e corrija-a, explicando o porquê.`,
            7: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico serão os pronomes demonstrativos. Siga estes passos:\n1. Explique a diferença entre 'this', 'that', 'these' e 'those'.\n2. Dê um exemplo visual (descrevendo objetos virtuais perto e longe).\n3. Peça-me para criar uma frase usando 'these'.\n4. Espere pela minha resposta e dê feedback.`,
            8: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é a revisão do Módulo 1. Siga estes passos:\n1. Diga que vamos fazer uma revisão rápida.\n2. Peça-me para me apresentar em inglês (nome e nacionalidade).\n3. Faça-me soletrar uma palavra (ex: 'FAMILY').\n4. Dê feedback sobre a minha apresentação e soletração.`,
            9: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o Simple Present para rotinas. Siga estes passos:\n1. Explique que usamos o Simple Present para hábitos e rotinas.\n2. Dê 3 exemplos de verbos de rotina (wake up, have lunch, go to bed).\n3. Peça-me para criar uma frase sobre a minha rotina usando um desses verbos.\n4. Espere pela minha resposta e corrija-a.`,
            10: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é a regra do '-s' para he/she/it. Siga estes passos:\n1. Explique que para 'he', 'she' e 'it', o verbo geralmente ganha um '-s'.\n2. Dê 3 exemplos (He works, She plays, It rains).\n3. Crie um exercício para eu completar: "My brother ___ (live) in another city.".\n4. Espere pela minha resposta e explique a correção.`,
            11: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são perguntas com 'Do' e 'Does'. Siga estes passos:\n1. Explique que usamos 'Do' para I/you/we/they e 'Does' para he/she/it.\n2. Dê um exemplo de cada: "Do you like coffee?", "Does he play tennis?".\n3. Peça-me para transformar a frase "She likes pizza" numa pergunta.\n4. Espere pela minha resposta e corrija-a.`,
            12: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são negativas com 'don't' e 'doesn't'. Siga estes passos:\n1. Explique que usamos 'don't' para I/you/we/they e 'doesn't' para he/she/it.\n2. Dê um exemplo de cada: "I don't smoke.", "She doesn't work here.".\n3. Peça-me para transformar a frase "He speaks French" numa negativa.\n4. Espere pela minha resposta e corrija-a.`,
            13: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são os pronomes objeto. Siga estes passos:\n1. Mostre-me uma lista: I -> me, you -> you, he -> him, she -> her, it -> it, we -> us, they -> them.\n2. Dê uma frase de exemplo: "I like her.".\n3. Crie um exercício para eu completar: "She gave the book to ___ (I).".\n4. Espere pela minha resposta e corrija-a.`,
            14: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são advérbios de frequência. Siga estes passos:\n1. Ensine-me a ordem de frequência: always > usually > sometimes > never.\n2. Explique que eles vêm ANTES do verbo principal (ex: "I always drink coffee.").\n3. Peça-me para criar uma frase sobre mim usando 'sometimes'.\n4. Espere pela minha resposta e verifique a posição do advérbio.`,
            15: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é dizer as horas. Siga estes passos:\n1. Explique a diferença entre 'a.m.' (manhã) e 'p.m.' (tarde/noite).\n2. Ensine a estrutura simples: "It's [hora] [minutos]." (ex: "It's two fifteen.").\n3. Pergunte-me "What time is it now?".\n4. Espere pela minha resposta e ajude-me a dizê-la corretamente.`,
            16: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é uma revisão do Módulo 2. Siga estes passos:\n1. Diga que vamos fazer uma revisão rápida.\n2. Crie um exercício para eu completar com 'don't' ou 'doesn't': "He ___ like rainy days.".\n3. Espere pela minha resposta e corrija-a.\n4. Pergunte-me "What time do you usually go to bed?".`,
            17: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o possessivo 's. Siga estes passos:\n1. Explique que usamos 's para mostrar posse (ex: "Maria's book").\n2. Dê 2 exemplos: um com nome singular e um com nome plural terminado em 's' (ex: "my parents' house").\n3. Peça-me para reescrever a frase "The name of my dog is Max." usando 's.\n4. Espere pela minha resposta e corrija-a.`,
            18: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é falar sobre profissões. Siga estes passos:\n1. Ensine-me a pergunta "What do you do?".\n2. Dê 3 exemplos de resposta: "I'm a student.", "I'm an engineer.", "I work in marketing.".\n3. Pergunte-me "What do you do?".\n4. Espere pela minha resposta e ajude-me a formulá-la corretamente.`,
            19: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é 'There is' e 'There are'. Siga estes passos:\n1. Explique que usamos 'There is' para singular e 'There are' para plural.\n2. Dê um exemplo de cada.\n3. Peça-me para descrever o que há nesta sala (virtualmente) usando 'There is' ou 'There are'.\n4. Espere pela minha resposta e dê feedback.`,
            20: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são preposições de lugar. Siga estes passos:\n1. Ensine-me o significado de 3 preposições: 'in', 'on', 'under'.\n2. Dê um exemplo para cada uma (ex: "The cat is in the box.").\n3. Crie um exercício para eu completar: "The books are ___ the table.".\n4. Espere pela minha resposta e corrija-a.`,
            21: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é 'How much' e 'How many'. Siga estes passos:\n1. Explique a diferença: 'How many' para contáveis, 'How much' para incontáveis.\n2. Dê um exemplo para cada.\n3. Crie um exercício para eu escolher a opção correta: "___ (How much/How many) water do you drink?".\n4. Espere pela minha resposta e explique a correção.`,
            22: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é 'a little' e 'a few'. Siga estes passos:\n1. Explique a diferença: 'a few' para contáveis, 'a little' para incontáveis.\n2. Dê um exemplo para cada.\n3. Crie um exercício para eu escolher a opção correta: "I have ___ (a little/a few) friends.".\n4. Espere pela minha resposta e explique a correção.`,
            23: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o modal 'can'. Siga estes passos:\n1. Explique que 'can' é usado para habilidades (eu sei fazer) e permissão (eu posso fazer).\n2. Dê um exemplo de cada.\n3. Peça-me para criar uma frase sobre uma habilidade que eu tenho.\n4. Espere pela minha resposta e dê feedback.`,
            24: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o Present Continuous. Siga estes passos:\n1. Explique que o usamos para ações que estão a acontecer AGORA (verbo 'to be' + verbo com '-ing').\n2. Dê um exemplo: "I am talking to you.".\n3. Pergunte-me: "What are you doing right now?".\n4. Espere pela minha resposta e ajude-me a usar a estrutura correta.`,
            25: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é a diferença entre Simple Present e Present Continuous. Siga estes passos:\n1. Explique: Simple Present para rotinas, Present Continuous para o agora.\n2. Dê um exemplo claro que mostre a diferença: "I usually drink tea, but today I am drinking coffee.".\n3. Crie um exercício para eu completar: "She ___ (work) in a bank, but she ___ (not work) today.".\n4. Espere pela minha resposta e corrija-a.`,
            26: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é a revisão do Módulo 3. Siga estes passos:\n1. Diga que vamos fazer uma revisão rápida.\n2. Crie um exercício para eu escolher entre Simple Present e Present Continuous: "Listen! The baby ___ (cry).".\n3. Espere pela minha resposta e corrija-a.\n4. Pergunte-me: "Can you swim?".`,
            27: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o passado de 'to be' (was/were). Siga estes passos:\n1. Explique quando usar 'was' (I, he, she, it) e 'were' (you, we, they).\n2. Dê um exemplo de cada.\n3. Crie um exercício para eu completar: "We ___ at home yesterday.".\n4. Espere pela minha resposta e explique a correção.`,
            28: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o Simple Past para verbos regulares. Siga estes passos:\n1. Explique que para verbos regulares no passado, geralmente adicionamos '-ed'.\n2. Dê 3 exemplos: "work -> worked", "play -> played", "study -> studied".\n3. Peça-me para colocar o verbo 'watch' no passado numa frase.\n4. Espere pela minha resposta e corrija-a.`,
            29: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico são perguntas e negativas no Simple Past. Siga estes passos:\n1. Explique que usamos 'did' para perguntar e 'didn't' para negar, e que o verbo principal volta ao normal.\n2. Dê um exemplo: "Did you work yesterday? No, I didn't work.".\n3. Peça-me para transformar a frase "He played tennis" numa pergunta.\n4. Espere pela minha resposta e corrija-a.`,
            30: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é o futuro com 'going to'. Siga estes passos:\n1. Explique que usamos 'am/is/are + going to + verbo' para falar de planos futuros.\n2. Dê um exemplo: "I am going to travel next month.".\n3. Pergunte-me: "What are you going to do this weekend?".\n4. Espere pela minha resposta e ajude-me a usar a estrutura correta.`,
            31: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é uma revisão final do A1. Siga estes passos:\n1. Diga que vamos fazer uma revisão final.\n2. Pergunte-me algo no presente: "What do you do?".\n3. Pergunte-me algo no passado: "What did you do yesterday?".\n4. Pergunte-me algo no futuro: "What are you going to do tomorrow?".`,
            32: `Estou aprendendo inglês.\nAja como o meu tutor de inglês. O tópico é a preparação para o projeto final. Siga estes passos:\n1. Explique que o projeto será uma pequena apresentação sobre a minha vida.\n2. Dê-me 3 dicas para uma boa apresentação (ex: "Use frases simples", "Fale devagar", "Faça contacto visual").\n3. Pergunte-me qual será o primeiro tópico da minha apresentação.`
        }
    },
    conversation: {
        titles: [
            "", "Dreams & Ambitions", "Love & Relationships", "Rebellion & Freedom",
            "City Life vs. Country Life", "Friendship", "Overcoming Challenges",
            "Travel & Adventure", "Work & Career", "Technology & Social Media",
            "Happiness & Life Philosophy", "The Supernatural & Mysteries", "Memory & Nostalgia",
            "Crime & Justice", "Food & Culture", "Success & Failure",
            "The Future & AI", "Learning & Education", "Animals & Nature"
        ],
        prompts: { // Prompts de REVISÃO (aula concluída)
            1: `The entire conversation MUST be in English.\nAct as a career coach. The topic is dreams and ambitions.\nFollow these steps:\n1. Start the conversation by asking me: "What is the difference between a dream and a goal in your opinion?".\n2. After I answer, ask me about a long-term ambition I have and why it's important to me.\n3. During our conversation, introduce and explain the meaning of the idiom "the sky's the limit".`,
            2: `The entire conversation MUST be in English.\nAct as a relationship counselor. The topic is love and relationships.\nFollow these steps:\n1. Present me with this dilemma: "Some say that passion is the most important element to sustain a long-term relationship, while others argue that friendship is the key."\n2. Ask for my opinion on this topic and ask me to provide a reason.\n3. Gently challenge my viewpoint by presenting the opposite perspective.\n4. During our chat, try to use and explain the phrase "to be on the same page".`,
            3: `The entire conversation MUST be in English.\nAct as a journalist exploring the concept of freedom. The topic is rebellion and freedom.\nFollow these steps:\n1. Start by asking me: "Can true freedom exist without some form of rebellion, either personal or social?".\n2. Listen to my answer and then ask for a real-world example to support my view.\n3. Introduce a counter-argument. For example, if I agree, you can suggest that stability is more important than rebellion.\n4. During our talk, introduce and explain the concept of "civil disobedience".`,
            4: `The entire conversation MUST be in English.\nAct as a partner in a debate. The topic is City Life vs. Country Life.\nFollow these steps:\n1. State the motion of the debate: "This house believes that living in the countryside provides a better quality of life than living in a major city."\n2. Ask me to choose a side and present my main argument.\n3. After I speak, you must take the opposing side and present a strong counter-argument.\n4. During the debate, introduce and explain the idiom "the best of both worlds".`,
            5: `The entire conversation MUST be in English.\nAct as a sociologist studying friendship. The topic is the nature of modern friendship.\nFollow these steps:\n1. Start with this observation: "With social media, it's easier than ever to have hundreds of 'friends'. But some argue these connections are superficial."\n2. Ask me the question: "In your opinion, what is the true definition of a friend in the digital age?".\n3. Ask me a follow-up question about the difference between a "close friend" and an "acquaintance".\n4. During our conversation, try to use and explain the expression "a friend in need is a friend indeed".`,
            6: `The entire conversation MUST be in English.\nAct as a life coach. The topic is overcoming challenges.\nFollow these steps:\n1. Start by asking me to think about a significant challenge I've faced in my life.\n2. Ask me: "What was the biggest lesson you learned from that experience?".\n3. Based on my answer, ask a follow-up question about how that lesson helps me today.\n4. Introduce and explain the idiom "every cloud has a silver lining".`,
            7: `The entire conversation MUST be in English.\nAct as an experienced backpacker. The topic is travel and adventure.\nFollow these steps:\n1. Tell me about a fictional, amazing place you've "visited".\n2. Ask me: "If you could travel anywhere in the world, with no budget limits, where would you go and why?".\n3. Listen to my answer and ask a question about the kind of activities I would do there.\n4. Introduce and explain the expression "to get itchy feet".`,
            8: `The entire conversation MUST be in English.\nAct as a senior manager in a company. The topic is work and career.\nFollow these steps:\n1. Present this scenario: "Imagine you have to choose between a job that you love but pays poorly, and a job that you find boring but pays very well."\n2. Ask me: "Which one would you choose and what are your reasons?".\n3. Challenge my decision by highlighting the main benefit of the other option.\n4. Introduce and explain the phrase "to climb the career ladder".`,
            9: `The entire conversation MUST be in English.\nAct as a technology journalist. The topic is social media.\nFollow these steps:\n1. Start with this premise: "Some say social media is a powerful tool for connection, while others call it a source of anxiety."\n2. Ask for my opinion: "What is your personal experience? Has it been more of a positive or a negative force in your life?".\n3. Based on my answer, ask a follow-up question.\n4. Introduce and explain the term "digital footprint".`,
            10: `The entire conversation MUST be in English.\nAct as a philosopher. The topic is happiness.\nFollow these steps:\n1. Ask me the classic question: "If you could have one of these three things for the rest of your life, which would you choose: unlimited wealth, true love, or profound wisdom?".\n2. Ask me to justify my choice.\n3. Gently argue for one of the options I didn't choose, to deepen the discussion.\n4. Introduce and explain the concept of "hedonic treadmill".`,
            11: `The entire conversation MUST be in English.\nAct as an investigator of mysteries. The topic is the supernatural.\nFollow these steps:\n1. Tell me a very short, mysterious story (e.g., about a strange noise in an old house).\n2. Ask me: "Do you believe in ghosts or supernatural phenomena? Why or why not?".\n3. Listen to my answer and show curiosity, asking a follow-up question.\n4. Introduce and explain the idiom "to make your blood run cold".`,
            12: `The entire conversation MUST be in English.\nAct as a childhood friend. The topic is memory and nostalgia.\nFollow these steps:\n1. Start by saying: "I was just thinking about the good old days...".\n2. Ask me: "What's a sound, smell, or song that instantly takes you back to your childhood?".\n3. After I answer, ask me to describe the memory associated with it.\n4. Introduce and explain the expression "to take a trip down memory lane".`,
            13: `The entire conversation MUST be in English.\nAct as a law student. The topic is crime and justice.\nFollow these steps:\n1. Present a moral dilemma: "Is it ever acceptable for a person to steal, for example, to feed their starving family?".\n2. Ask for my opinion and my reasoning.\n3. Challenge my reasoning by presenting the legal perspective versus the moral one.\n4. Introduce and explain the concept of a "grey area".`,
            14: `The entire conversation MUST be in English.\nAct as a food critic. The topic is food and culture.\nFollow these steps:\n1. Start by saying: "I believe that to truly understand a culture, you must first understand its food.".\n2. Ask me: "What is a traditional dish from your culture, and what does it say about your country?".\n3. Ask me a follow-up question about the ingredients or how it's prepared.\n4. Introduce and explain the idiom "the proof is in the pudding".`,
            15: `The entire conversation MUST be in English.\nAct as a business mentor. The topic is success and failure.\nFollow these steps:\n1. Ask me the question: "Which is a better teacher: success or failure? Please explain why.".\n2. Listen to my answer and challenge it by arguing for the opposite viewpoint.\n3. Ask me to think of a famous person who exemplifies my point of view.\n4. Introduce and explain the expression "to learn from your mistakes".`,
            16: `The entire conversation MUST be in English.\nAct as a futurist. The topic is the future and AI.\nFollow these steps:\n1. Present this question: "In 50 years, what is one job that you think will be completely automated by AI, and one job that will still need a human?".\n2. Ask me to justify both of my choices.\n3. Offer your own opinion on one of my choices.\n4. Introduce and explain the concept of a "paradigm shift".`,
            17: `The entire conversation MUST be in English.\nAct as a university professor. The topic is learning and education.\nFollow these steps:\n1. Pose the question: "What is more valuable for a successful career: the knowledge you gain in university, or the soft skills like communication and teamwork?".\n2. Ask for my opinion and reasoning.\n3. Gently challenge my view by emphasizing the importance of the other side.\n4. Introduce and explain the concept of a "learning curve".`,
            18: `The entire conversation MUST be in English.\nAct as a wildlife documentarian. The topic is animals and nature.\nFollow these steps:\n1. Start with this statement: "Humans have a responsibility to protect endangered species."\n2. Ask me: "What do you think is the single most important thing we can do to protect the planet's biodiversity?".\n3. Listen to my idea and ask a follow-up question about how it could be implemented.\n4. Introduce and explain the term "domino effect" in the context of ecosystems.`
        },
        preview_prompts: { // Prompts de PREPARAÇÃO (próxima aula)
            1: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about Dreams & Ambitions.\nFollow these steps:\n1. Explain the difference between 'ambition', 'goal', and 'dream'.\n2. Give me one example sentence for each.\n3. Ask me to create my own sentence using the word 'ambition'.\n4. Wait for my answer and provide feedback.`,
            2: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about Love & Relationships.\nFollow these steps:\n1. Teach me 3 advanced adjectives to describe a good partner (e.g., supportive, reliable, thoughtful).\n2. Give me an example sentence for one of them.\n3. Ask me to describe the qualities of a good friend, encouraging me to use one of the new adjectives.\n4. Wait for my answer and provide feedback.`,
            3: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about Rebellion & Freedom.\nFollow these steps:\n1. Explain the meaning of the expression "to stand up for what you believe in".\n2. Give a simple example.\n3. Ask me a question: "Think about a time you had to stand up for something. What was it?".\n4. Wait for my answer and help me express it in English if needed.`,
            4: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a debate about City vs. Country life.\nFollow these steps:\n1. Provide me with two phrases for expressing opinions (e.g., "In my view...", "From my perspective...").\n2. Provide me with two phrases for disagreeing politely (e.g., "I see your point, but...", "I respectfully disagree because...").\n3. Start a mini-debate by saying "I believe city life is more exciting. What do you think?".\n4. Wait for my response and encourage me to use the new phrases.`,
            5: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about Friendship.\nFollow these steps:\n1. Teach me two English idioms about friendship (e.g., "birds of a feather flock together", "to see eye to eye").\n2. Explain their meanings briefly.\n3. Ask me to try and use one of them in a sentence about my own friends.\n4. Wait for my answer and provide feedback.`,
            6: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about overcoming challenges.\nFollow these steps:\n1. Explain the meaning of the word "resilience".\n2. Give me an example sentence.\n3. Ask me to describe a situation that requires resilience.\n4. Wait for my answer and provide feedback.`,
            7: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about travel.\nFollow these steps:\n1. Explain the difference between 'travel', 'trip', and 'journey'.\n2. Give me an example for each.\n3. Ask me "What was the most memorable trip you've ever taken?".\n4. Wait for my answer and ask a follow-up question.`,
            8: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about careers.\nFollow these steps:\n1. Teach me 3 "power verbs" for a resume (e.g., "managed", "developed", "achieved").\n2. Ask me to make a sentence about my professional experience using one of them.\n3. Wait for my answer and provide feedback.`,
            9: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about technology.\nFollow these steps:\n1. Explain the term "digital detox".\n2. Give me one example sentence.\n3. Ask me for my opinion: "Do you think digital detoxes are a good idea?".\n4. Wait for my answer and ask me why I think so.`,
            10: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about happiness.\nFollow these steps:\n1. Explain the difference between "fun" and "happiness".\n2. Ask me to describe something that is "fun" for me, and something that brings me "happiness".\n3. Wait for my answer and comment on it.`,
            11: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about mysteries.\nFollow these steps:\n1. Teach me 3 words related to mystery: "clue", "suspect", "alibi".\n2. Give me an example sentence using one of them.\n3. Ask me to create a sentence with the word "suspect".\n4. Wait for my answer and provide feedback.`,
            12: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about nostalgia.\nFollow these steps:\n1. Explain the meaning of the adjective "bittersweet".\n2. Give an example of a bittersweet memory.\n3. Ask me to describe a "bittersweet" memory of my own.\n4. Wait for my answer and offer a kind comment.`,
            13: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about justice.\nFollow these steps:\n1. Explain the difference between "justice" and "revenge".\n2. Ask me for my opinion: "Is a life sentence a fair punishment for all serious crimes?".\n3. Wait for my answer and ask a follow-up question.`,
            14: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about food.\nFollow these steps:\n1. Teach me 3 advanced adjectives to describe food texture (e.g., "creamy", "crunchy", "tender").\n2. Give an example for each.\n3. Ask me to describe my favorite food using one of these words.\n4. Wait for my answer and provide feedback.`,
            15: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about success and failure.\nFollow these steps:\n1. Explain the meaning of the proverb "Failure is the mother of success.".\n2. Ask me if I agree with this statement and why.\n3. Wait for my answer and ask for a personal example.`,
            16: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about AI.\nFollow these steps:\n1. Explain the term "AI ethics".\n2. Ask me for my opinion: "What is the biggest ethical concern we should have about AI?".\n3. Wait for my answer and ask me to elaborate on my point.`,
            17: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about education.\nFollow these steps:\n1. Explain the difference between "knowledge" and "wisdom".\n2. Ask me: "What is something you have knowledge about, and what is something you have wisdom in?".\n3. Wait for my answer and comment on the distinction.`,
            18: `The entire conversation MUST be in English.\nAct as my English tutor. I'm preparing for a class about nature.\nFollow these steps:\n1. Explain the concept of a "carbon footprint".\n2. Give an example of how to reduce it.\n3. Ask me to name one thing I do in my daily life to help the environment.\n4. Wait for my answer and provide encouragement.`
        }
    },
    vestibular: {
        titles: [
            "", "Introduction to Vestibular", "Skimming & Scanning", "Identifying Main Ideas",
            "Understanding Vocabulary in Context", "Interpreting Cartoons and Comics", "Analyzing Literary Texts"
        ],
        prompts: { // Prompts de REVISÃO (aula concluída)
            1: `Estou a preparar-me para o vestibular.\nAja como um examinador. O tópico é a estrutura das provas de inglês. Siga estes passos:\n1. Apresente-me uma pequena passagem de um texto típico de vestibular (científico ou jornalístico).\n2. Faça-me uma pergunta de múltipla escolha sobre a ideia geral do texto.\n3. Espere pela minha resposta e explique por que a alternativa correta é a melhor.`,
            2: `Estou a preparar-me para o vestibular.\nAja como meu tutor. O tópico são as técnicas de Skimming e Scanning. Siga estes passos:\n1. Dê-me um texto de 3 parágrafos e um limite de 30 segundos para eu ler (usando a técnica de skimming).\n2. Após os 30 segundos, peça-me para dizer qual é o tema principal do texto.\n3. Depois, peça-me para encontrar (usando scanning) uma data ou um nome específico no texto.\n4. Verifique as minhas respostas.`,
            3: `Estou a preparar-me para o vestibular.\nAja como meu tutor. O tópico é identificar a ideia principal. Siga estes passos:\n1. Apresente-me um parágrafo de um artigo de opinião.\n2. Peça-me para resumir a ideia principal desse parágrafo numa única frase em português.\n3. Analise o meu resumo e dê-me feedback sobre a clareza e precisão.`,
        },
        preview_prompts: { // Prompts de PREPARAÇÃO (próxima aula)
            1: `Estou a preparar-me para o vestibular.\nAja como meu tutor de inglês. Vou começar a estudar para as provas de vestibular. Siga estes passos:\n1. Explique brevemente os 3 tipos mais comuns de questões de inglês no vestibular (Interpretação de Texto, Vocabulário, Gramática).\n2. Dê um exemplo simples para cada tipo.\n3. Pergunte-me em qual dessas áreas eu sinto mais dificuldade.`,
            2: `Estou a preparar-me para o vestibular.\nAja como meu tutor de inglês. A próxima aula será sobre Skimming e Scanning. Siga estes passos:\n1. Explique a diferença entre Skimming (leitura rápida para ideia geral) e Scanning (procura por informação específica).\n2. Dê um exemplo prático: "Para saber o tema de uma notícia, você usa ___. Para encontrar o nome de uma pessoa no texto, você usa ___."\n3. Peça-me para completar as lacunas.`,
            3: `Estou a preparar-me para o vestibular.\nAja como meu tutor de inglês. A próxima aula será sobre como identificar a ideia principal. Siga estes passos:\n1. Explique que a ideia principal (main idea) é a mensagem central do autor.\n2. Dê a dica de que ela geralmente está na primeira ou na última frase do parágrafo.\n3. Dê-me um parágrafo curto e peça para eu tentar sublinhar a frase que contém a ideia principal.`,
        }
    },
    // NOVO MÓDULO DE BUSINESS
    business: {
        titles: [
            "", // Posição 0 vazia
            "The Job Interview", "Describing Skills", "Answering Questions", 
            "Networking & Small Talk", "Professional Emails", "Business Phone Calls", "Participating in Meetings",
            "Giving a Presentation", "Describing Trends & Data", "The Art of Negotiation", "Describing Your Company", "Marketing & Branding",
            "Talking About Finance", "Problem-Solving", "Intercultural Communication", "Leadership Styles"
        ],
        prompts: { // Prompts de REVISÃO (aula concluída)
            1: `I'm learning Business English.\nAct as my English career coach. The topic is job interviews. Follow these steps:\n1. Start a mock interview with me by asking the classic question: "So, tell me a little bit about yourself."\n2. Wait for my answer.\n3. Then, ask me a follow-up question about my professional experience, like "Why are you interested in this position?".\n4. After I answer, provide one piece of feedback on my response.`,
            2: `I'm learning Business English.\nAct as a hiring manager. The topic is describing skills. Follow these steps:\n1. Ask me the question: "What are your greatest strengths?".\n2. Wait for my answer.\n3. After I list a strength, ask me to provide a specific example of when I used that skill in a professional situation.\n4. Give me feedback on whether my example was clear and effective.`,
            3: `I'm learning Business English.\nAct as an interviewer. The topic is answering tough questions. Follow these steps:\n1. Ask me a common behavioral question, for example: "Tell me about a time you faced a challenge at work and how you handled it."\n2. Remind me to use the STAR technique (Situation, Task, Action, Result) in my answer.\n3. Wait for my response and evaluate how well I structured it using STAR.`
            // Você pode adicionar os prompts para as outras lições aqui
        },
        preview_prompts: { // Prompts de PREPARAÇÃO (próxima aula)
            1: `I'm preparing for a Business English class about Job Interviews.\nAct as my English tutor. Follow these steps:\n1. Teach me 3 powerful verbs to describe professional achievements (e.g., 'achieved', 'managed', 'implemented').\n2. Give me a clear example for each verb.\n3. Ask me to create a sentence about myself using one of them.\n4. Wait for my answer and give me feedback.`,
            2: `I'm preparing for a Business English class about Describing Skills.\nAct as my English tutor. Follow these steps:\n1. Explain the difference between "hard skills" (technical abilities, like programming) and "soft skills" (interpersonal abilities, like communication).\n2. Give me two examples of each.\n3. Ask me to identify one of my main hard skills and one of my main soft skills.\n4. Wait for my answer.`,
            3: `I'm preparing for a Business English class about Answering Questions using the STAR technique.\nAct as my English tutor. Follow these steps:\n1. Briefly explain what each letter in STAR stands for: Situation, Task, Action, Result.\n2. Give a very simple, one-sentence example for each part (e.g., Situation: "The website was down." Task: "My task was to fix it." etc.).\n3. Ask me which part of STAR I think is the most important for showing my contribution.`,
            // Você pode adicionar os prompts para as outras lições aqui
        }
    }
};