(function(){
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    R.register(28,R.lesson({
        title:'On the Phone',
        objectives:['Iniciar, manter e encerrar uma ligação simples.','Pedir para falar com alguém e deixar recado.','Usar can e could em pedidos telefônicos frequentes.','Confirmar nomes, números, horários e convites por telefone.'],
        intro:[line('Emma','Hello. Can I speak to Sabrina, please?','Alô. Posso falar com a Sabrina, por favor?'),line('Leo','I’m sorry, she isn’t available right now. Who’s calling?','Desculpe, ela não está disponível agora. Quem está falando?'),line('Emma','This is Emma. Could you ask her to call me back?','Aqui é a Emma. Poderia pedir para ela me retornar?'),line('Leo','Of course. Can I have your number?','Claro. Pode me dar seu número?'),line('Emma','It’s 555-0184.','É 555-0184.'),line('Leo','Let me repeat that: 555-0184.','Deixe-me repetir: 555-0184.')],
        vocab:[v('call','ligar; ligação','I’ll call you tonight.','Vou ligar para você hoje à noite.'),v('answer','atender; responder','Can you answer the phone?','Pode atender o telefone?'),v('available','disponível','She isn’t available.','Ela não está disponível.'),v('busy','ocupado; linha ocupada','The line is busy.','A linha está ocupada.'),v('hold','aguardar na linha','Please hold.','Aguarde, por favor.'),v('message','recado; mensagem','Can I leave a message?','Posso deixar um recado?'),v('call back','retornar ligação','Please call me back.','Por favor, retorne minha ligação.'),v('wrong number','número errado','Sorry, wrong number.','Desculpe, número errado.'),v('voicemail','correio de voz','Leave a voicemail.','Deixe uma mensagem de voz.'),v('line','linha telefônica','The line is bad.','A linha está ruim.'),v('hear','ouvir','I can’t hear you.','Não consigo ouvir você.'),v('repeat','repetir','Could you repeat that?','Poderia repetir?'),v('spell','soletrar','Could you spell your name?','Poderia soletrar seu nome?'),v('speak','falar','Can I speak to Emma?','Posso falar com a Emma?'),v('leave','deixar','I’d like to leave a message.','Gostaria de deixar um recado.'),v('reach','conseguir contato','You can reach me after six.','Você consegue falar comigo depois das seis.'),v('hang up','desligar','Don’t hang up.','Não desligue.'),v('phone number','número de telefone','What’s your phone number?','Qual é seu número de telefone?')],
        grammar:{title:'Phone requests with can and could',summary:'Can e could formam pedidos com o verbo base. Could soa mais educado; não é necessário ensinar um novo tempo verbal aqui.',rows:[['ask to speak','Can/Could I speak to...?', 'Could I speak to Sabrina?', 'Poderia falar com Sabrina?'],['request','Can/Could you + base verb?', 'Could you repeat that?', 'Poderia repetir?'],['offer message','Can I take a message?', 'Can I take a message?', 'Posso anotar um recado?'],['identify caller','This is + name.', 'This is Emma.', 'Aqui é a Emma.'],['confirm','Let me repeat...', 'Let me repeat the number.', 'Deixe-me repetir o número.'],['future contact','will + base verb','I’ll call you back.', 'Vou retornar sua ligação.']],notes:['Ao telefone, diga This is Emma, não I am Emma.', 'Can/Could you repeat...? usa verbo base.', 'Soletre nomes e leia números em blocos curtos.']},
        activitySections:[activity('Build the phone call','Coloque cada frase na etapa adequada da ligação.',[p('Order','goodbye · identify caller · greet · ask to speak · leave message','greet · ask to speak · identify caller · leave message · goodbye'),p('Complete','Can I ___ to Sabrina?','speak'),p('Complete','Who’s ___?','calling'),p('Complete','This ___ Emma.','is'),p('Complete','Please ___. I’ll check.','hold'),p('Complete','Can I leave a ___?','message'),p('Complete','Could you ask her to call me ___?','back'),p('Complete','Sorry, ___ number.','wrong'),p('Choose','Telefone: (I am Emma / This is Emma).','This is Emma'),p('Create','Open a call and ask for Daniel.','Hello. Can I speak to Daniel, please?')],'Call Structure'),activity('Polite requests and confirmation','Transforme pedidos e confirme informações críticas.',[p('Make polite','Repeat that.','Could you repeat that, please?'),p('Make polite','Spell your name.','Could you spell your name, please?'),p('Make polite','Call me after six.','Could you call me after six, please?'),p('Build','message / take / Can / I / a / ?', 'Can I take a message?'),p('Build','number / have / Can / your / I / ?', 'Can I have your number?'),p('Answer','The line is bad.','I’m sorry. I can’t hear you. Could you repeat that?'),p('Confirm','Name: Sean = S-E-A-N','Let me spell that: S-E-A-N.'),p('Confirm','Number: 555-0179','Let me repeat that: 555-0179.'),p('Confirm','Meeting: Friday at 6:45','So that’s Friday at six forty-five.'),p('Correct','Could you to repeat?','Could you repeat?'),p('Correct','I’m Emma. (on the phone)','This is Emma.')]),activity('Messages and invitations','Registre recados completos e responda a convites.',[p('Take a message','Caller Ana · call back · after 7 · 555-0192','Ana called. Please call her back after seven at 555-0192.'),p('Take a message','Meeting moved · Saturday · 2:30','The meeting moved to Saturday at two thirty.'),p('Answer','Would you like to come on Sunday? accept','I’d love to. What time?'),p('Answer','Would you like to come tonight? decline','I’m sorry, I can’t. I have plans.'),p('Ask','invite Sabrina to lunch on Friday','Would you like to have lunch on Friday?'),p('Change','Friday 7:00 → Saturday 6:30','Can we change it to Saturday at six thirty?'),p('Correct','Tell her call me back.','Tell her to call me back. / Ask her to call me back.'),p('Create','Leave a full voicemail: identity, reason, number, callback time.','Hi, this is... I’m calling about... Please call me back at...'),p('Create','Complete a call with one misunderstanding and confirmation.','Could you repeat...? Let me confirm...')],'Messages')],
        translations:[t('Posso falar com a Sabrina?','Can I speak to Sabrina?'),t('Quem está falando?','Who’s calling?'),t('Aqui é a Emma.','This is Emma.'),t('Ela não está disponível agora.','She isn’t available right now.'),t('Aguarde, por favor.','Please hold.'),t('Posso deixar um recado?','Can I leave a message?'),t('Poderia repetir?','Could you repeat that?'),t('Poderia soletrar seu nome?','Could you spell your name?'),t('Peça para ela me retornar.','Ask her to call me back.'),t('Deixe-me confirmar o número.','Let me confirm the number.')],
        expressions:[x('Can I speak to...?', 'Posso falar com...?', 'Pedido principal ao telefone.','Can I speak to Daniel?','Posso falar com Daniel?'),x('Who’s calling?', 'Quem está falando?', 'Pede identificação.','May I ask who’s calling?','Posso perguntar quem está falando?'),x('This is...', 'Aqui é...', 'Identificação ao telefone.','This is Emma.','Aqui é a Emma.'),x('Please hold.', 'Aguarde, por favor.','Pede espera na linha.','Please hold for a moment.','Aguarde um momento.'),x('Can I leave/take a message?', 'Posso deixar/anotar um recado?', 'Gerencia recado.','Can I take a message?','Posso anotar um recado?'),x('call me back', 'me retornar','Pedido de retorno.','Could you call me back?','Poderia me retornar?'),x('The line is bad.', 'A linha está ruim.','Explica problema de áudio.','The line is bad. I can’t hear you.','A linha está ruim. Não consigo ouvir.'),x('Let me confirm...', 'Deixe-me confirmar...','Evita erro.','Let me confirm the time.','Deixe-me confirmar o horário.'),x('Sorry, wrong number.', 'Desculpe, número errado.','Encerra ligação errada.','I’m sorry, wrong number.','Desculpe, número errado.')],
        dialogues:[
            dialogue('Calling Sabrina',line('A','Good afternoon. Can I speak to Sabrina, please?','Boa tarde. Posso falar com Sabrina, por favor?'),line('B','Of course. Who’s calling?','Claro. Quem está falando?'),line('A','This is Daniel from her English class.','Aqui é Daniel, da turma de inglês dela.'),line('B','One moment, please.','Um momento, por favor.'),line('A','Sure.','Claro.'),line('B','I’m connecting you now.','Vou transferir agora.')),
            dialogue('Leaving a message',line('A','I’m sorry, Sabrina isn’t available right now.','Desculpe, Sabrina não está disponível agora.'),line('B','Can I leave a message?','Posso deixar um recado?'),line('A','Of course.','Claro.'),line('B','Please tell her the class starts at seven tonight.','Por favor, diga a ela que a aula começa às sete hoje à noite.'),line('A','Does she have your number?','Ela tem seu número?'),line('B','Yes, she does. Thank you.','Sim. Obrigado.')),
            dialogue('A bad connection',line('A','Hello? The line is bad. I can’t hear you.','Alô? A linha está ruim. Não consigo ouvir você.'),line('B','Can you hear me now?','Consegue me ouvir agora?'),line('A','Only a little. Where are you?','Só um pouco. Onde você está?'),line('B','I’m on the bus.','Estou no ônibus.'),line('A','Okay. I’ll call you back in ten minutes.','Certo. Vou retornar em dez minutos.'),line('B','Great. Talk to you soon.','Ótimo. Falamos em breve.')),
            dialogue('Confirming a number',line('A','My number is 555-0194.','Meu número é 555-0194.'),line('B','Let me repeat that: 555-0194.','Deixe-me repetir: 555-0194.'),line('A','That’s correct.','Está correto.'),line('B','Great. I’ll call after six.','Ótimo. Vou ligar depois das seis.')),
            dialogue('A Saturday invitation',line('A','Would you like to come to my house on Saturday?','Gostaria de vir à minha casa no sábado?'),line('B','I’d love to. What time?','Eu adoraria. Que horas?'),line('A','How about seven?','Que tal às sete?'),line('B','Seven is perfect. Should I bring anything?','Sete está perfeito. Devo levar alguma coisa?'),line('A','You can bring some juice.','Você pode levar um pouco de suco.'),line('B','Okay. See you on Saturday.','Certo. Vejo você no sábado.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('Three phone messages','Sabrina was away from her phone for one hour. Leo took three messages. First, Emma called about Saturday’s barbecue. The time changed from one to two thirty. Then Daniel called because he is going to bring drinks, but he needs the address. Finally, the doctor’s office called. Sabrina’s appointment is now on Monday at a quarter past ten. Leo repeated every number and time before he ended each call.',question('Who took the messages?','Leo did.'),question('What changed about the barbecue?','The time changed to two thirty.'),question('Why did Daniel call?','He needs the address.'),question('When is the appointment?','On Monday at a quarter past ten.'),question('What did Leo confirm?','Every number and time.')),
        conversation:{questions:['Open and close a phone call.','Ask to speak to three people.','Identify yourself correctly.','Say someone is unavailable and offer to take a message.','Spell a name and dictate a number.','Ask for repetition because the line is bad.','Leave a complete message.','Handle an invitation whose time changes.'],support:['Can I speak to...?', 'This is...', 'Please hold.', 'Can I take a message?', 'Could you repeat...?', 'Let me confirm...', 'I’ll call back.']},
        homework:homework('Prepare três roteiros telefônicos completos.', ['Pessoa indisponível','Linha ruim','Convite com mudança de horário'],['Cada ligação tem abertura, propósito, confirmação e encerramento.','Usei can/could em pedidos.','Registrei nomes, números e horários sem ambiguidade.']),
        mission:{title:'Handle the call',task:'Atenda uma ligação, registre um recado completo e resolva uma mudança de horário.',focus:['phone language','polite requests','confirmation']}
    }));
    R.get(28).dialogues.push(
        dialogue('Wrong number',line('A','Hello. Can I speak to Emma?','Alô. Posso falar com Emma?'),line('B','I’m sorry, wrong number.','Desculpe, número errado.')),
        dialogue('Voicemail',line('A','Hi, this is Daniel. Please call me back after six.','Oi, aqui é Daniel. Por favor, retorne depois das seis.'),line('B','Message saved.','Mensagem salva.'))
    );
}());
