(function () {
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    R.register(17,R.lesson({
        title:'Is It Yours or Mine?',
        objectives:['Perguntar a quem pertence um objeto com whose.','Distinguir possessive adjectives e possessive pronouns.','Confirmar e corrigir posse em situações cotidianas.','Usar all e every em blocos simples.'],
        intro:[line('Emma','Whose phone is this? Is it yours?','De quem é este telefone? É seu?'),line('Sarah','No, mine is black. Maybe it’s Daniel’s.','Não, o meu é preto. Talvez seja do Daniel.'),line('Daniel','Yes, it’s mine. Thanks.','Sim, é meu. Obrigado.'),line('Emma','And are these keys yours too?','E estas chaves também são suas?'),line('Daniel','No. My keys are here. Those are hers.','Não. Minhas chaves estão aqui. Aquelas são dela.'),line('Sarah','Yes, they’re mine. I lose them every day!','Sim, são minhas. Eu as perco todos os dias!')],
        vocab:[v('belong to','pertencer a','The phone belongs to Daniel.','O telefone pertence ao Daniel.'),v('owner','dono(a)','Who is the owner?','Quem é o dono?'),v('mine','meu/minha','The black phone is mine.','O telefone preto é meu.'),v('yours','seu/sua','Is this bag yours?','Esta bolsa é sua?'),v('his','dele','The blue jacket is his.','A jaqueta azul é dele.'),v('hers','dela','Those keys are hers.','Aquelas chaves são dela.'),v('ours','nosso(a)','The apartment is ours.','O apartamento é nosso.'),v('theirs','deles/delas','The shoes are theirs.','Os sapatos são deles.'),v('wallet','carteira','Whose wallet is this?','De quem é esta carteira?'),v('ID card','documento de identidade','This ID card is hers.','Este documento é dela.'),v('headphones','fones de ouvido','Are the headphones yours?','Os fones são seus?'),v('charger','carregador','My charger is white.','Meu carregador é branco.'),v('lost and found','achados e perdidos','Take it to lost and found.','Leve para achados e perdidos.'),v('all','todos(as)','All the bags are here.','Todas as bolsas estão aqui.'),v('every','todo(a); cada','I check my bag every day.','Confiro minha bolsa todos os dias.'),v('same','mesmo(a)','We have the same phone.','Temos o mesmo telefone.')],
        grammar:{title:'Possessive adjectives x possessive pronouns',summary:'Adjetivos possessivos vêm antes de um substantivo; pronomes possessivos substituem o substantivo.',rows:[
            ['I','my + noun → mine','This is my bag. The bag is mine.','Esta é minha bolsa. A bolsa é minha.'],['you','your → yours','Is this your phone? Is it yours?','Este telefone é seu?'],
            ['he','his → his','His jacket is blue. The blue jacket is his.','A jaqueta azul é dele.'],['she','her → hers','Her keys are here. These keys are hers.','Estas chaves são dela.'],
            ['we','our → ours','Our house is small. It is ours.','A casa é nossa.'],['they','their → theirs','Their shoes are black. They are theirs.','Os sapatos são deles.']
        ],notes:['Não use substantivo depois de mine, yours, hers, ours ou theirs.', 'His tem a mesma forma nas duas funções.', 'Whose pergunta posse; who’s é a contração de who is.']},
        activitySections:[
            activity('My/mine, your/yours e outras formas','Escolha se a frase precisa de substantivo depois da forma possessiva.',[
                p('Choose','This is (my / mine) phone.','my'),p('Choose','This phone is (my / mine).','mine'),p('Choose','Is this (your / yours) bag?','your'),p('Choose','Is this bag (your / yours)?','yours'),
                p('Choose','These are (her / hers) keys.','her'),p('Choose','These keys are (her / hers).','hers'),p('Choose','That is (our / ours) house.','our'),p('Choose','That house is (our / ours).','ours'),
                p('Choose','Those are (their / theirs) shoes.','their'),p('Choose','Those shoes are (their / theirs).','theirs'),
                p('Correct','This is mine phone.','This is my phone.'),p('Correct','The jacket is her.','The jacket is hers.')
            ],'Possessive Forms'),
            activity('Whose is it?','Forme perguntas de posse e responda com o pronome adequado.',[
                p('Build','phone / Whose / this / is / ?','Whose phone is this?'),p('Build','keys / are / Whose / these / ?','Whose keys are these?'),
                p('Answer','Whose wallet is this? Owner: Daniel','It is Daniel’s. / It is his.'),p('Answer','Whose headphones are these? Owner: Sarah','They are Sarah’s. / They are hers.'),
                p('Answer','Is this your charger? Positive.','Yes, it’s mine.'),p('Answer','Are these your keys? Negative.','No, they aren’t mine.'),
                p('Transform','This is Emma’s bag. → possessive pronoun','This bag is hers.'),p('Transform','Those are our books. → possessive pronoun','Those books are ours.'),
                p('Correct','Who’s phone is this?','Whose phone is this?'),p('Correct','These keys are my.','These keys are mine.'),
                p('Describe','Phone: Daniel · keys: Sarah · bags: Emma and Sarah','The phone is his. The keys are hers. The bags are theirs.')
            ]),
            activity('All e every em contexto','Use all antes de um grupo e every antes de singular.',[
                p('Choose','(All / Every) the bags are here.','All'),p('Choose','I check my bag (all / every) day.','every'),p('Choose','(All / Every) student has an ID card.','Every'),
                p('Choose','(All / Every) the phones are black.','All'),p('Complete','We have the ___ charger.','same'),p('Complete','Take the wallet to lost and ___.','found'),
                p('Correct','Every the bags are here.','All the bags are here.'),p('Correct','I check my phone all day. (cada dia)','I check my phone every day.'),
                p('Create','Say one thing you do every day.','I ... every day.'),p('Create','Say something true about all the items in an imaginary box.','All the ... are ...')
            ],'More Practice')
        ],
        translations:[t('De quem é este telefone?','Whose phone is this?'),t('É seu?','Is it yours?'),t('Não, o meu é preto.','No, mine is black.'),t('O telefone é dele.','The phone is his.'),t('Estas chaves são dela.','These keys are hers.'),t('A casa é nossa.','The house is ours.'),t('Aqueles sapatos são deles.','Those shoes are theirs.'),t('Todas as bolsas estão aqui.','All the bags are here.'),t('Eu confiro minha bolsa todos os dias.','I check my bag every day.'),t('Leve para achados e perdidos.','Take it to lost and found.')],
        expressions:[x('Whose ... is this?','De quem é este/esta...?', 'Pergunta por dono singular.','Whose wallet is this?','De quem é esta carteira?'),x('Whose ... are these?','De quem são estes/estas...?', 'Pergunta por dono plural.','Whose keys are these?','De quem são estas chaves?'),x('Is it yours?','É seu/sua?', 'Confirma posse singular.','Is this phone yours?','Este telefone é seu?'),x('Are they yours?','São seus/suas?', 'Confirma posse plural.','Are these headphones yours?','Estes fones são seus?'),x('It’s mine/his/hers.','É meu/dele/dela.','Resposta sem repetir o objeto.','The wallet is hers.','A carteira é dela.'),x('They’re ours/theirs.','São nossos/deles.','Resposta plural de posse.','The books are ours.','Os livros são nossos.'),x('It belongs to...','Pertence a...', 'Outra forma de identificar o dono.','It belongs to Daniel.','Pertence ao Daniel.'),x('Maybe it’s...','Talvez seja...', 'Hipótese simples sobre o dono.','Maybe it’s Sarah’s.','Talvez seja da Sarah.'),x('lost and found','achados e perdidos','Local para objetos encontrados.','Take it to lost and found.','Leve para achados e perdidos.')],
        dialogues:[
            dialogue('A phone on the table',line('A','Whose phone is this?','De quem é este telefone?'),line('B','Let me see. The black phone is mine.','Deixe-me ver. O telefone preto é meu.'),line('A','This one is blue. Is it Julia’s?','Este é azul. É da Julia?'),line('B','Yes, it’s hers.','Sim, é dela.'),line('A','Can you give it to her?','Você pode entregá-lo a ela?'),line('B','Sure.','Claro.')),
            dialogue('Two sets of keys',line('A','Are these keys yours?','Estas chaves são suas?'),line('B','No. Mine are here in my bag.','Não. As minhas estão aqui na minha bolsa.'),line('A','Maybe they’re Leo’s.','Talvez sejam do Leo.'),line('B','No, his are on a red key ring.','Não, as dele estão em um chaveiro vermelho.'),line('A','Then let’s ask Sarah.','Então vamos perguntar à Sarah.')),
            dialogue('A black wallet',line('A','Maybe this wallet is Daniel’s.','Talvez esta carteira seja do Daniel.'),line('B','No, his is brown. This one is black.','Não, a dele é marrom. Esta é preta.'),line('A','Is your wallet black?','Sua carteira é preta?'),line('B','Yes, but mine is in my pocket.','Sim, mas a minha está no meu bolso.'),line('A','Let’s take this one to lost and found.','Vamos levar esta para os achados e perdidos.'),line('B','Good idea.','Boa ideia.')),
            dialogue('Sarah’s headphones',line('A','Whose headphones are these?','De quem são estes fones?'),line('B','They belong to Sarah. They’re hers.','Pertencem à Sarah. São dela.'),line('A','Are you sure?','Você tem certeza?'),line('B','Yes. Her name is on them.','Sim. O nome dela está neles.')),
            dialogue('At lost and found',line('A','Excuse me. This ID card isn’t mine.','Com licença. Este documento não é meu.'),line('B','Whose is it?','De quem é?'),line('A','I think it’s Ethan’s.','Acho que é do Ethan.'),line('B','His photo and name are on it.','A foto e o nome dele estão nele.'),line('A','Can I leave it here?','Posso deixá-lo aqui?'),line('B','Yes. We can call him.','Sim. Podemos ligar para ele.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('A box of lost items','There is a box at the school’s lost and found. The black phone is Daniel’s; it is his. The red wallet belongs to Sarah; it is hers. The white headphones are Emma and Sarah’s; they are theirs. The blue charger is ours because it belongs to the English class. All the items have an owner, but one ID card is still in the box.',question('Whose phone is in the box?','It is Daniel’s. It is his.'),question('What belongs to Sarah?','The red wallet is hers.'),question('Whose headphones are they?','They are Emma and Sarah’s. They are theirs.'),question('Why is the charger ours?','It belongs to the English class.'),question('What is still in the box?','One ID card is still in the box.')),
        conversation:{questions:['Name five objects you carry every day.','Choose one object and say it is yours.','Ask who owns three imaginary objects.','Answer with mine, yours, his, hers, ours and theirs.','Say something you do every day.','Describe all the items in an imaginary lost-and-found box.','Correct two wrong ownership guesses.','Complete a lost-and-found conversation.'],support:['Whose ... is this?','Is it yours?','It’s mine/his/hers.','They’re ours/theirs.','It belongs to...','Maybe it’s...']},
        homework:homework('Crie um inventário de achados e perdidos com oito objetos e diferentes donos.',['Objetos em uma escola','Itens esquecidos em uma casa','Achados e perdidos de um hotel'],['Usei possessive adjectives e pronouns.','Incluí perguntas com whose.','Usei all, every e belong to em contexto.']),
        mission:{title:'Lost-and-found desk',task:'Identifique os donos de vários objetos, corrija hipóteses erradas e organize o que ainda não tem dono.',focus:['whose','possessive pronouns','confirmação de posse']}
    }));
}());
