(function(){
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
    R.register(21,R.lesson({
        title:'Vacation Calendar',
        objectives:['Nomear meses e organizar datas no calendário.','Usar números ordinais nas datas mais frequentes.','Dizer onde alguém estava com was/were.','Perguntar e responder sobre datas e lugares no passado.'],
        intro:[line('Emma','When was your vacation?','Quando foram suas férias?'),line('Daniel','It was in July, from the third to the seventeenth.','Foram em julho, do dia três ao dia dezessete.'),line('Emma','Where were you?','Onde você estava?'),line('Daniel','I was in Bahia with my family.','Eu estava na Bahia com minha família.'),line('Emma','Was the weather good?','O tempo estava bom?'),line('Daniel','Yes, it was. The beaches were beautiful.','Sim. As praias eram lindas.')],
        vocab:[...months.map((m,i)=>v(m,['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'][i],`My vacation is in ${m}.`,`Minhas férias são em ${['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'][i]}.`)),v('first','primeiro(a)','January first.','Primeiro de janeiro.'),v('second','segundo(a)','May second.','Dois de maio.'),v('third','terceiro(a)','July third.','Três de julho.'),v('fourth','quarto(a)','April fourth.','Quatro de abril.'),v('fifth','quinto(a)','August fifth.','Cinco de agosto.'),v('vacation','férias','My vacation was in July.','Minhas férias foram em julho.'),v('holiday','feriado','The holiday was on Monday.','O feriado foi na segunda-feira.'),v('calendar','calendário','Check the calendar.','Confira o calendário.'),v('last','passado(a); último(a)','I was there last month.','Eu estava lá no mês passado.')],
        grammar:{title:'Dates and past of be',summary:'Use was com I/he/she/it e were com you/we/they para estados e lugares no passado.',rows:[['I/he/she/it','was / wasn’t','I was in Bahia.','Eu estava na Bahia.'],['you/we/they','were / weren’t','We were on vacation.','Nós estávamos de férias.'],['question','Was + subject...?','Was it hot?','Estava quente?'],['question','Were + subject...?','Were they at the hotel?','Eles estavam no hotel?'],['date','month + ordinal','July third','três de julho'],['year','in + year','in 2025','em 2025']],notes:['Em inglês americano: July 3rd. Ao falar: July third.', 'Use on com data e in com mês ou ano.', 'Respostas curtas: Yes, I was. No, they weren’t.']},
        afterVocabularySlides:[{eyebrow:'Calendar Guide',title:'Months and dates',content:`<div class="calendar-reference"><p><strong>Months:</strong> ${months.join(' · ')}</p><p><strong>Dates:</strong> 1st first · 2nd second · 3rd third · 4th fourth · 5th fifth · 8th eighth · 9th ninth · 12th twelfth · 20th twentieth · 21st twenty-first · 30th thirtieth · 31st thirty-first</p><p><strong>Examples:</strong> July 3rd = July third · December 25th = December twenty-fifth</p></div>`}],
        activitySections:[
            activity('Calendar language','Leia meses, datas e anos em voz alta e complete o calendário.',[p('Order','March · January · February','January · February · March'),p('Order','October · December · November','October · November · December'),p('Write','1st','first'),p('Write','2nd','second'),p('Write','3rd','third'),p('Write','12th','twelfth'),p('Write','21st','twenty-first'),p('Say the date','07/03 (US format)','July third'),p('Say the date','12/25 (US format)','December twenty-fifth'),p('Complete','My birthday is ___ May.','in'),p('Complete','The trip is ___ August 14th.','on'),p('Answer','When is your birthday?','My birthday is on ...')],'Dates'),
            activity('Was or were?','Complete e transforme frases sobre férias passadas.',[p('Complete','I ___ on vacation in July.','was'),p('Complete','We ___ in Bahia.','were'),p('Complete','The hotel ___ small.','was'),p('Complete','The rooms ___ comfortable.','were'),p('Make negative','It was cold.','It wasn’t cold.'),p('Make negative','They were at the beach.','They weren’t at the beach.'),p('Make a question','Daniel was in Bahia.','Was Daniel in Bahia?'),p('Make a question','The beaches were busy.','Were the beaches busy?'),p('Answer','Were you at home yesterday?','Yes, I was. / No, I wasn’t.'),p('Correct','We was on vacation.','We were on vacation.'),p('Correct','Was they at the hotel?','Were they at the hotel?')]),
            activity('A past calendar','Combine data, pessoa, lugar e descrição em frases completas.',[p('Describe','Daniel · July 3–17 · Bahia','Daniel was in Bahia from July third to July seventeenth.'),p('Describe','Emma and Sarah · December 20–27 · São Paulo','Emma and Sarah were in São Paulo from December twentieth to December twenty-seventh.'),p('Answer','When was the holiday? May 1','It was on May first.'),p('Answer','Where were you last weekend?','I was in/at ...'),p('Answer','Was the weather good? positive','Yes, it was.'),p('Correct','My vacation was on July.','My vacation was in July.'),p('Correct','The trip was in August fifth.','The trip was on August fifth.'),p('Create','Give three dates that are important to you.','... is on ...'),p('Create','Say where two people were last month.','... was/were ... last month.')],'Use the Calendar')
        ],
        translations:[t('Quando foram suas férias?','When was your vacation?'),t('Foram em julho.','It was in July.'),t('Onde você estava?','Where were you?'),t('Eu estava na Bahia.','I was in Bahia.'),t('Nós estávamos de férias.','We were on vacation.'),t('Eles não estavam no hotel.','They weren’t at the hotel.'),t('Estava quente?','Was it hot?'),t('As praias eram bonitas?','Were the beaches beautiful?'),t('A viagem foi no dia três de julho.','The trip was on July third.'),t('Meu aniversário é no dia vinte e um de maio.','My birthday is on May twenty-first.')],
        expressions:[x('When was...?', 'Quando foi...?', 'Pergunta por uma data passada.','When was your trip?','Quando foi sua viagem?'),x('Where were you?', 'Onde você estava?', 'Pergunta por lugar no passado.','Where were you last weekend?','Onde você estava no fim de semana passado?'),x('from ... to...', 'de ... até...', 'Marca início e fim.','from July third to July seventeenth','de três a dezessete de julho'),x('last month/year','mês/ano passado','Referência de passado.','I was there last year.','Eu estava lá no ano passado.'),x('on vacation','de férias','Estado de férias.','We were on vacation.','Nós estávamos de férias.'),x('What was it like?', 'Como foi?', 'Pede uma descrição.','What was the hotel like?','Como era o hotel?'),x('It was great.', 'Foi ótimo.','Avaliação simples.','The trip was great.','A viagem foi ótima.')],
        dialogues:[
            dialogue('Vacation dates',line('A','When was your vacation?','Quando foram suas férias?'),line('B','It was in July.','Foram em julho.'),line('A','What were the exact dates?','Quais eram as datas exatas?'),line('B','From July tenth to July twentieth.','De dez de julho a vinte de julho.'),line('A','Was it a long vacation?','Foram férias longas?'),line('B','No, but it was great.','Não, mas foram ótimas.')),
            dialogue('In Salvador',line('A','Where were you in July?','Onde você estava em julho?'),line('B','I was in Salvador.','Eu estava em Salvador.'),line('A','Were you near the beach?','Você estava perto da praia?'),line('B','Yes. My hotel was across from the beach.','Sim. Meu hotel ficava em frente à praia.')),
            dialogue('The hotel',line('A','What was the hotel like?','Como era o hotel?'),line('B','It was small but comfortable.','Era pequeno, mas confortável.'),line('A','Was your room quiet?','Seu quarto era silencioso?'),line('B','Yes, it was. The room was very nice.','Sim. O quarto era muito bom.'),line('A','Were the people friendly?','As pessoas eram simpáticas?'),line('B','Yes, they were very friendly.','Sim, elas eram muito simpáticas.')),
            dialogue('Sunny days',line('A','Was it sunny every day?','Estava ensolarado todos os dias?'),line('B','No. Monday was rainy.','Não. Segunda-feira foi chuvosa.'),line('A','And Tuesday?','E terça-feira?'),line('B','Tuesday was warm and sunny.','Terça-feira foi quente e ensolarada.')),
            dialogue('Friends on vacation',line('A','Were your friends with you?','Seus amigos estavam com você?'),line('B','No, they weren’t.','Não.'),line('A','Who was with you?','Quem estava com você?'),line('B','My sister and my parents were with me.','Minha irmã e meus pais estavam comigo.'),line('A','Were they happy with the hotel?','Eles estavam satisfeitos com o hotel?'),line('B','Yes, they were.','Sim.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('Daniel’s vacation calendar','Daniel was on vacation from July third to July seventeenth. From the third to the ninth, he was in Salvador with his parents. The weather was sunny and the beaches were busy. From the tenth to the seventeenth, they were in a small town. The hotel wasn’t modern, but the rooms were clean and comfortable. His birthday was on July twelfth, so the trip was special.',question('When was Daniel on vacation?','From July third to July seventeenth.'),question('Where was he first?','He was in Salvador.'),question('What were the beaches like?','They were busy.'),question('Was the hotel modern?','No, it wasn’t.'),question('When was his birthday?','On July twelfth.')),
        conversation:{questions:['Name all twelve months.','Say today’s date.','Say your birthday.','Give three holiday dates.','Say where you were last weekend.','Describe where two family members were last month.','Ask and answer four questions with was/were.','Describe a past vacation calendar.'],support:['on + date','in + month/year','I was...','We were...','Was it...?', 'Were they...?', 'from ... to...']},
        homework:homework('Monte um calendário de um mês passado e descreva onde as pessoas estavam.',['Férias','Datas de família','Um mês especial'],['Incluí pelo menos oito datas por extenso.','Usei was/were em afirmações, negativas e perguntas.','Usei on, in e from...to corretamente.']),
        mission:{title:'Build the vacation calendar',task:'Organize datas, lugares e pessoas de uma viagem passada e responda a mudanças no calendário.',focus:['months and dates','was/were','past location']}
    }));
}());
