(function(){
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    R.register(24,R.lesson({
        title:'What Was Happening?',
        objectives:['Descrever uma ação em andamento em um momento passado.','Formar Past Continuous com was/were + verbo-ing.','Contrastar contexto em andamento e evento curto no Past Simple.','Perguntar o que pessoas estavam fazendo durante um problema de viagem.'],
        intro:[line('Emma','What were you doing when the flight was canceled?','O que você estava fazendo quando o voo foi cancelado?'),line('Daniel','I was waiting at the gate and talking to Sarah.','Eu estava esperando no portão e conversando com Sarah.'),line('Emma','Were people boarding?','As pessoas estavam embarcando?'),line('Daniel','No, they weren’t. Some people were sleeping.','Não. Algumas pessoas estavam dormindo.'),line('Emma','What happened next?','O que aconteceu depois?'),line('Daniel','An agent made an announcement and everyone stood up.','Uma funcionária fez um anúncio e todos se levantaram.')],
        vocab:[v('cancel','cancelar','They canceled the flight.','Eles cancelaram o voo.'),v('announcement','anúncio','The agent made an announcement.','A funcionária fez um anúncio.'),v('sleep','dormir','Some passengers were sleeping.','Alguns passageiros estavam dormindo.'),v('read','ler','I was reading a book.','Eu estava lendo um livro.'),v('charge','carregar bateria','She was charging her phone.','Ela estava carregando o telefone.'),v('rain','chover','It was raining.','Estava chovendo.'),v('drive','dirigir','Daniel was driving.','Daniel estava dirigindo.'),v('cross','atravessar','We were crossing the street.','Estávamos atravessando a rua.'),v('hear','ouvir','I heard an announcement.','Ouvi um anúncio.'),v('fall','cair','The suitcase fell.','A mala caiu.'),v('suddenly','de repente','Suddenly, the lights went out.','De repente, as luzes apagaram.'),v('while','enquanto','I read while I was waiting.','Li enquanto estava esperando.'),v('when','quando','I was waiting when they called me.','Eu estava esperando quando me chamaram.'),v('at that moment','naquele momento','At that moment, everyone was quiet.','Naquele momento, todos estavam quietos.')],
        grammar:{title:'Past Continuous',summary:'Use was/were + verbo-ing para uma ação em andamento em um ponto do passado. Use Past Simple para o evento concluído que acontece dentro desse contexto.',rows:[['I/he/she/it','was + verb-ing','I was waiting.','Eu estava esperando.'],['you/we/they','were + verb-ing','They were sleeping.','Eles estavam dormindo.'],['negative','wasn’t/weren’t + verb-ing','We weren’t boarding.','Não estávamos embarcando.'],['question','Was/Were + subject + verb-ing?','Were you waiting?','Você estava esperando?'],['interruption','continuous + when + simple','I was waiting when they called.','Eu esperava quando chamaram.'],['parallel actions','while + continuous','She was reading while he was sleeping.','Ela lia enquanto ele dormia.']],notes:['Was/were sozinho descreve estado: I was tired. Com -ing, descreve ação: I was waiting.', 'When costuma introduzir o evento curto; while destaca a ação em andamento.', 'Mantenha as regras de -ing aprendidas na lição 18.']},
        activitySections:[activity('Build the past scene','Complete com was/were e a forma -ing.',[p('Complete','I ___ (wait) at the gate.','was waiting'),p('Complete','They ___ (sleep).','were sleeping'),p('Complete','Sarah ___ (charge) her phone.','was charging'),p('Complete','We ___ (look for) the counter.','were looking for'),p('Make negative','Daniel was driving.','Daniel wasn’t driving.'),p('Make negative','The passengers were boarding.','The passengers weren’t boarding.'),p('Make a question','Emma was reading.','Was Emma reading?'),p('Make a question','They were talking.','Were they talking?'),p('Answer','Were you sleeping at 10 last night?','Yes, I was. / No, I wasn’t.'),p('Correct','They was waiting.','They were waiting.'),p('Correct','Was you reading?','Were you reading?')],'Past Scene'),activity('When and while','Escolha o tempo adequado para o contexto e para o evento concluído.',[p('Complete','I ___ (wait) when the agent ___ (call) my name.','was waiting; called'),p('Complete','They ___ (sleep) when the lights ___ (go) out.','were sleeping; went'),p('Complete','Daniel ___ (drive) when it ___ (start) to rain.','was driving; started'),p('Complete','The suitcase ___ (fall) while we ___ (walk).','fell; were walking'),p('Combine','Sarah was reading. Daniel was sleeping.','Sarah was reading while Daniel was sleeping.'),p('Combine','We were boarding. The announcement started.','We were boarding when the announcement started.'),p('Choose','The action in progress: (Past Simple / Past Continuous)','Past Continuous'),p('Choose','The short completed event: (Past Simple / Past Continuous)','Past Simple'),p('Correct','I waited when the phone was ringing.','I was waiting when the phone rang.'),p('Create','Give one background action and one interruption.','I was ...ing when ...')]),activity('Investigate the moment','Faça perguntas para reconstruir o que cada pessoa estava fazendo.',[p('Build','doing / What / you / were / ?', 'What were you doing?'),p('Build','she / Was / waiting / ?', 'Was she waiting?'),p('Answer','What was Daniel doing? drive','He was driving.'),p('Answer','Were the passengers boarding? negative','No, they weren’t.'),p('Answer','What happened while you were waiting?','... happened while I was waiting.'),p('Describe','8:00: Emma—read; Sarah—charge phone; Daniel—buy water','At eight, Emma was reading, Sarah was charging her phone and Daniel was buying water.'),p('Retell','waiting → announcement → stand up → flight canceled','We were waiting when an agent made an announcement. Everyone stood up. Then they canceled the flight.'),p('Create','Ask five questions about a travel problem.','What were you doing...? Was/Were ...ing? What happened?')],'Question the Scene')],
        translations:[t('O que você estava fazendo?','What were you doing?'),t('Eu estava esperando no portão.','I was waiting at the gate.'),t('Eles estavam dormindo.','They were sleeping.'),t('Nós não estávamos embarcando.','We weren’t boarding.'),t('Ela estava lendo?','Was she reading?'),t('Sim, ela estava.','Yes, she was.'),t('Eu estava esperando quando me chamaram.','I was waiting when they called me.'),t('A mala caiu enquanto caminhávamos.','The suitcase fell while we were walking.'),t('De repente, as luzes apagaram.','Suddenly, the lights went out.'),t('O voo foi cancelado.','The flight was canceled.')],
        expressions:[x('What were you doing?', 'O que você estava fazendo?', 'Pergunta pela ação em andamento.','What were you doing at eight?','O que você estava fazendo às oito?'),x('At that moment,...','Naquele momento,...','Localiza uma cena no passado.','At that moment, we were waiting.','Naquele momento, estávamos esperando.'),x('while I was...', 'enquanto eu estava...', 'Mantém a ação de fundo.','while I was sleeping','enquanto eu estava dormindo'),x('when ... happened', 'quando ... aconteceu','Introduz o evento.','when the lights went out','quando as luzes apagaram'),x('Suddenly,...','De repente,...','Marca mudança inesperada.','Suddenly, everyone stood up.','De repente, todos se levantaram.'),x('What happened next?', 'O que aconteceu depois?', 'Mantém o relato avançando.','What happened next?','O que aconteceu depois?'),x('The flight was canceled.', 'O voo foi cancelado.','Resultado essencial de viagem.','Our flight was canceled.','Nosso voo foi cancelado.')],
        dialogues:[
            dialogue('Waiting at eight',line('A','What were you doing at eight?','O que você estava fazendo às oito?'),line('B','I was waiting at the gate.','Eu estava esperando no portão.'),line('A','Were you traveling alone?','Você estava viajando sozinho?'),line('B','No. My sister was traveling with me.','Não. Minha irmã estava viajando comigo.'),line('A','What was she doing?','O que ela estava fazendo?'),line('B','She was buying coffee.','Ela estava comprando café.')),
            dialogue('The announcement',line('A','Were you sleeping when the announcement started?','Você estava dormindo quando o anúncio começou?'),line('B','No, I was reading.','Não, eu estava lendo.'),line('A','What was the announcement about?','Sobre o que era o anúncio?'),line('B','A new gate for our flight.','Um novo portão para nosso voo.'),line('A','What was the new gate number?','Qual era o número do novo portão?'),line('B','It was gate thirty-one.','Era o portão trinta e um.')),
            dialogue('Rain on the road',line('A','What happened while you were driving?','O que aconteceu enquanto você dirigia?'),line('B','It started to rain.','Começou a chover.'),line('A','Was the traffic moving?','O trânsito estava andando?'),line('B','No. Everyone was driving very slowly.','Não. Todos estavam dirigindo muito devagar.'),line('A','Did you arrive on time?','Você chegou no horário?'),line('B','No, I missed my flight.','Não, perdi meu voo.')),
            dialogue('A canceled flight',line('A','Were people boarding when you arrived?','As pessoas estavam embarcando quando você chegou?'),line('B','No. Everyone was waiting at the gate.','Não. Todos estavam esperando no portão.'),line('A','What was happening?','O que estava acontecendo?'),line('B','The airline was giving people new tickets.','A companhia aérea estava dando novas passagens às pessoas.'),line('A','Why?','Por quê?'),line('B','Because the flight was canceled.','Porque o voo foi cancelado.')),
            dialogue('Leaving the airport',line('A','What happened after the cancellation?','O que aconteceu depois do cancelamento?'),line('B','We collected our luggage.','Pegamos nossa bagagem.'),line('A','Was your family waiting outside?','Sua família estava esperando do lado de fora?'),line('B','No. They were driving to the airport.','Não. Eles estavam dirigindo para o aeroporto.'),line('A','What did you do while you waited?','O que você fez enquanto esperava?'),line('B','We had dinner and called the hotel.','Jantamos e ligamos para o hotel.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('When the lights went out','At nine last night, Daniel was waiting for a flight. Emma was reading, Sarah was buying coffee and two children were sleeping near their parents. While an agent was talking, the lights suddenly went out. People stopped talking and the children woke up. A minute later, the lights came back. Then the agent announced that the flight was canceled because it was raining heavily.',question('What was Daniel doing?','He was waiting for a flight.'),question('Who was reading?','Emma was reading.'),question('What were the children doing?','They were sleeping.'),question('What happened while the agent was talking?','The lights went out.'),question('Why was the flight canceled?','Because it was raining heavily.')),
        conversation:{questions:['Say what you were doing at three times yesterday.','Ask what another person was doing.','Describe five actions at an airport at 8 p.m.','Add one sudden event to the scene.','Use when in three sentences.','Use while in two sentences.','Reconstruct a travel problem from clues.','Retell it after one fact changes.'],support:['I was ...ing.', 'They were ...ing.', 'Was/Were ...ing?', 'when...', 'while...', 'Suddenly...', 'What happened next?']},
        homework:homework('Crie uma narrativa visual com seis ações em andamento e três eventos que interrompem a cena.',['Aeroporto','Rua durante uma tempestade','Casa durante uma falta de energia'],['Usei Past Continuous e Past Simple com funções diferentes.','Incluí when, while e suddenly.','Preparei respostas para pelo menos seis perguntas.']),
        mission:{title:'Reconstruct the interruption',task:'Descubra o que cada pessoa estava fazendo antes, durante e depois de um problema de viagem.',focus:['Past Continuous','when/while','event sequence']}
    }));
}());
