(function(){
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    R.register(26,R.lesson({
        title:'Sabrina’s Invitation',
        objectives:['Falar sobre estações e condições do tempo.','Expressar planos e intenções com be going to.','Perguntar sobre planos futuros e responder com detalhes.','Tomar decisões práticas para um evento de acordo com a previsão.'],
        intro:[line('Sabrina','I’m going to have a barbecue on Saturday. Would you like to come?','Vou fazer um churrasco no sábado. Você gostaria de vir?'),line('Emma','I’d love to. Is it going to be sunny?','Eu adoraria. Vai fazer sol?'),line('Sabrina','I think so, but it’s going to be windy in the afternoon.','Acho que sim, mas vai ventar à tarde.'),line('Emma','What are you going to do if it rains?','O que você vai fazer se chover?'),line('Sabrina','We’re going to eat inside.','Vamos comer dentro de casa.'),line('Emma','Great. I’m going to bring a dessert.','Ótimo. Vou levar uma sobremesa.')],
        vocab:[v('spring','primavera','Spring is warm.','A primavera é amena.'),v('summer','verão','Summer is hot.','O verão é quente.'),v('fall','outono','Fall is cool.','O outono é fresco.'),v('winter','inverno','Winter is cold.','O inverno é frio.'),v('sunny','ensolarado','It is sunny today.','Está ensolarado hoje.'),v('cloudy','nublado','Tomorrow is going to be cloudy.','Amanhã vai ficar nublado.'),v('rainy','chuvoso','It is a rainy morning.','É uma manhã chuvosa.'),v('windy','ventando','It is windy outside.','Está ventando lá fora.'),v('hot','quente','It is very hot.','Está muito quente.'),v('warm','morno; ameno','The afternoon is warm.','A tarde está amena.'),v('cool','fresco','The evening is cool.','A noite está fresca.'),v('cold','frio','It is cold in winter.','Faz frio no inverno.'),v('forecast','previsão do tempo','Check the forecast.','Confira a previsão.'),v('temperature','temperatura','The temperature is twenty degrees.','A temperatura é vinte graus.'),v('barbecue','churrasco','We are going to have a barbecue.','Vamos fazer um churrasco.'),v('invite','convidar','Sabrina invited us.','Sabrina nos convidou.'),v('bring','levar; trazer','I’m going to bring dessert.','Vou levar sobremesa.'),v('inside','dentro','We can eat inside.','Podemos comer dentro.'),v('outside','fora','The tables are outside.','As mesas estão do lado de fora.')],
        grammar:{title:'Be going to',summary:'Use am/is/are going to + verbo base para planos, intenções e previsões apoiadas no que vemos ou sabemos.',rows:[['I','am going to + verb','I’m going to bring dessert.','Vou levar sobremesa.'],['he/she/it','is going to + verb','It’s going to rain.','Vai chover.'],['you/we/they','are going to + verb','We’re going to eat inside.','Vamos comer dentro.'],['negative','am not/isn’t/aren’t going to','She isn’t going to drive.','Ela não vai dirigir.'],['question','Am/Is/Are + subject + going to?','Are you going to come?','Você vai vir?'],['Wh-question','What/Where/When + be + subject + going to?','What are you going to bring?','O que você vai levar?']],notes:['O verbo depois de going to fica na forma base.', 'O presente de be concorda com o sujeito.', 'Para clima: It is sunny now; It is going to rain later.']},
        activitySections:[activity('Weather and seasons','Associe clima, estação e escolhas práticas.',[p('Match','summer · winter · spring · fall → hot · cold · warm · cool','summer—hot; winter—cold; spring—warm; fall—cool'),p('Choose','The sky has many clouds. It is (sunny / cloudy).','cloudy'),p('Choose','The trees are moving a lot. It is (windy / warm).','windy'),p('Complete','The ___ is twenty-eight degrees.','temperature'),p('Answer','What’s the weather like today?','It is ...'),p('Answer','What is your favorite season? Why?','My favorite season is ... because ...'),p('Plan','Sunny and hot → clothes/activity','I’m going to wear ... and ...'),p('Plan','Cold and rainy → clothes/activity','I’m going to ...'),p('Correct','It is sun today.','It is sunny today.'),p('Create','Give a three-day forecast.','On..., it is going to be...')],'Weather'),activity('Future plans','Complete e transforme planos com a forma correta de be.',[p('Complete','I ___ going to bring dessert.','am'),p('Complete','Sabrina ___ going to have a barbecue.','is'),p('Complete','We ___ going to eat inside.','are'),p('Complete','It ___ going to rain.','is'),p('Make negative','Emma is going to drive.','Emma isn’t going to drive.'),p('Make a question','They are going to come.','Are they going to come?'),p('Build','you / What / bring / going to / are / ?', 'What are you going to bring?'),p('Build','party / Where / going to / be / is / the / ?', 'Where is the party going to be?'),p('Answer','Are you going to study tonight?','Yes, I am. / No, I’m not.'),p('Correct','I going to make a cake.','I’m going to make a cake.'),p('Correct','She is going to brings drinks.','She is going to bring drinks.')]),activity('Plan around the forecast','Adapte o evento quando o tempo muda.',[p('Decide','Sunny → barbecue location','We’re going to have the barbecue outside.'),p('Decide','Rainy → barbecue location','We’re going to eat inside.'),p('Decide','Cold → clothes','I’m going to wear a jacket.'),p('Decide','Hot → drinks','I’m going to bring cold drinks.'),p('Answer','What are you going to do this weekend?','I’m going to ...'),p('Answer','Who are you going to invite?','I’m going to invite ...'),p('Answer','What are you going to bring?','I’m going to bring ...'),p('Change the plan','Outdoor picnic → heavy rain','We aren’t going to have a picnic outside. We’re going to ...'),p('Create','Plan a small event with date, time, place, food and weather alternative.','The event is on... We’re going to... If it rains, we’re going to...')],'Plan B')],
        translations:[t('Como está o tempo?','What’s the weather like?'),t('Está ensolarado e quente.','It is sunny and hot.'),t('Vai chover.','It is going to rain.'),t('Vou fazer um churrasco.','I’m going to have a barbecue.'),t('Você vai vir?','Are you going to come?'),t('O que você vai levar?','What are you going to bring?'),t('Ela não vai dirigir.','She isn’t going to drive.'),t('Vamos comer dentro de casa.','We’re going to eat inside.'),t('A previsão diz que vai ventar.','The forecast says it is going to be windy.'),t('Vou levar uma sobremesa.','I’m going to bring a dessert.')],
        expressions:[x('Would you like to come?', 'Você gostaria de vir?', 'Convite educado.','Would you like to come on Saturday?','Você gostaria de vir no sábado?'),x('I’d love to.', 'Eu adoraria.','Aceitação calorosa.','I’d love to. What time?','Eu adoraria. Que horas?'),x('What’s the weather like?', 'Como está o tempo?', 'Pergunta pelo clima.','What’s the weather like there?','Como está o tempo aí?'),x('It’s going to...', 'Vai...', 'Plano ou previsão.','It’s going to rain.','Vai chover.'),x('What are you going to...?', 'O que você vai...?', 'Pergunta por intenção.','What are you going to bring?','O que você vai levar?'),x('I think so.', 'Acho que sim.','Resposta cautelosa positiva.','Is it going to be sunny? I think so.','Vai fazer sol? Acho que sim.'),x('If it rains,...', 'Se chover,...','Bloco prático para plano alternativo.','If it rains, we’re going inside.','Se chover, vamos entrar.'),x('change of plans', 'mudança de planos','Nomeia uma alteração.','There is a change of plans.','Houve uma mudança de planos.')],
        dialogues:[
            dialogue('A barbecue invitation',line('A','Would you like to come to my barbecue on Saturday?','Gostaria de vir ao meu churrasco no sábado?'),line('B','I’d love to. What time is it?','Eu adoraria. Que horas vai ser?'),line('A','It’s going to start at one.','Vai começar à uma.'),line('B','Great. Who is going to be there?','Ótimo. Quem vai estar lá?'),line('A','My family and a few friends.','Minha família e alguns amigos.'),line('B','Perfect. See you on Saturday.','Perfeito. Vejo você no sábado.')),
            dialogue('Checking the forecast',line('A','Is it going to rain on Saturday?','Vai chover no sábado?'),line('B','No, but it’s going to be windy.','Não, mas vai ventar.'),line('A','Is it going to be cold?','Vai fazer frio?'),line('B','A little. The temperature is going to be sixteen degrees.','Um pouco. A temperatura vai ser de dezesseis graus.'),line('A','Then I’m going to take a sweater.','Então vou levar um suéter.'),line('B','Good idea.','Boa ideia.')),
            dialogue('What to bring',line('A','What are you going to bring?','O que você vai levar?'),line('B','I’m going to bring dessert.','Vou levar sobremesa.'),line('A','What kind of dessert?','Que tipo de sobremesa?'),line('B','A chocolate cake.','Um bolo de chocolate.')),
            dialogue('A plan for rain',line('A','What are we going to do if it rains?','O que vamos fazer se chover?'),line('B','We’re going to eat inside.','Vamos comer dentro.'),line('A','Is there enough space for everyone?','Há espaço suficiente para todos?'),line('B','Yes. There are two large tables in the living room.','Sim. Há duas mesas grandes na sala.'),line('A','And where are we going to cook?','E onde vamos cozinhar?'),line('B','We’re going to use the kitchen and the covered patio.','Vamos usar a cozinha e o pátio coberto.')),
            dialogue('Clothes for the evening',line('A','It’s going to be cold tonight.','Vai fazer frio hoje à noite.'),line('B','Really? I’m wearing a T-shirt.','Sério? Estou usando uma camiseta.'),line('A','The temperature is going to fall after six.','A temperatura vai cair depois das seis.'),line('B','Then I’m going to take a jacket.','Então vou levar uma jaqueta.'),line('A','Take an umbrella too.','Leve um guarda-chuva também.'),line('B','Okay. I have one in the car.','Certo. Tenho um no carro.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('Saturday’s plan','Sabrina is going to have a barbecue on Saturday at one o’clock. Twelve people are going to come. Emma is going to bring dessert, Daniel is going to buy drinks and Leo is going to bring music. The morning is going to be sunny and warm, but the forecast says it is going to rain after four. Sabrina has a plan: they are going to eat outside first and move inside if it rains.',question('What is Sabrina going to do?','She is going to have a barbecue.'),question('How many people are going to come?','Twelve.'),question('What is Emma going to bring?','Dessert.'),question('What is the afternoon forecast?','It is going to rain after four.'),question('What is the alternative plan?','They are going to move inside.')),
        conversation:{questions:['Name the four seasons.','Describe today’s weather.','Give a weekend forecast.','Say five plans for this week.','Ask four questions about another person’s plans.','Plan food and clothes for two types of weather.','Invite someone and answer.','Change the event plan after the forecast changes.'],support:['It is...', 'It’s going to...', 'I’m going to...', 'Are you going to...?', 'Would you like to...?', 'If it rains...']},
        homework:homework('Planeje um evento com previsão e duas alternativas.', ['Churrasco','Aniversário','Passeio ao ar livre'],['Incluí data, hora, local e convidados.','Usei going to em afirmações, negativas e perguntas.','Criei alternativas para duas mudanças de clima.']),
        mission:{title:'Weather-proof invitation',task:'Convide, organize contribuições e adapte o evento a uma mudança inesperada no tempo.',focus:['weather','going to','plan change']}
    }));
}());
