(function(){
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    R.register(23,R.lesson({
        title:'At the Airport',
        objectives:['Usar linguagem essencial de aeroporto e transporte.','Perguntar onde fazer check-in, embarcar e retirar bagagem.','Usar can/can’t para habilidade e possibilidade prática.','Usar know how to para conhecimento de como realizar uma ação.'],
        intro:[line('Agent','Good morning. Can I see your passport and ticket?','Bom dia. Posso ver seu passaporte e sua passagem?'),line('Daniel','Of course. Can I take this bag on the plane?','Claro. Posso levar esta bolsa no avião?'),line('Agent','Yes, you can, but you can’t take that large suitcase.','Sim, mas você não pode levar aquela mala grande.'),line('Daniel','Where can I check it in?','Onde posso despachá-la?'),line('Agent','At counter twelve. Then go to gate twenty-four.','No balcão doze. Depois vá ao portão vinte e quatro.'),line('Daniel','Thank you. I don’t know how to use the check-in machine.','Obrigado. Não sei usar a máquina de check-in.')],
        vocab:[v('airport','aeroporto','We arrived at the airport.','Chegamos ao aeroporto.'),v('flight','voo','My flight is at nine.','Meu voo é às nove.'),v('ticket','passagem; bilhete','Here is my ticket.','Aqui está minha passagem.'),v('passport','passaporte','Can I see your passport?','Posso ver seu passaporte?'),v('suitcase','mala','My suitcase is large.','Minha mala é grande.'),v('luggage','bagagem','Where is my luggage?','Onde está minha bagagem?'),v('check in','fazer check-in','I need to check in.','Preciso fazer check-in.'),v('counter','balcão','Go to counter twelve.','Vá ao balcão doze.'),v('gate','portão de embarque','Gate twenty-four is open.','O portão vinte e quatro está aberto.'),v('boarding pass','cartão de embarque','Here is your boarding pass.','Aqui está seu cartão de embarque.'),v('departure','partida','Check the departures screen.','Confira o painel de partidas.'),v('arrival','chegada','Arrivals are downstairs.','As chegadas ficam no andar de baixo.'),v('delayed','atrasado','The flight is delayed.','O voo está atrasado.'),v('on time','no horário','The flight is on time.','O voo está no horário.'),v('board','embarcar','We can board now.','Podemos embarcar agora.'),v('land','pousar','The plane landed at ten.','O avião pousou às dez.'),v('by plane','de avião','We traveled by plane.','Viajamos de avião.'),v('by bus/train/car','de ônibus/trem/carro','I went by bus.','Fui de ônibus.')],
        grammar:{title:'Can and know how to',summary:'Use can + verbo base para habilidade, permissão informal ou possibilidade. Use know how to + verbo para saber como fazer algo.',rows:[['ability','can + base verb','I can drive.','Eu sei/posso dirigir.'],['negative','can’t + base verb','I can’t swim.','Eu não sei/posso nadar.'],['question','Can + subject + base verb?','Can you help me?','Você pode me ajudar?'],['permission','Can I + base verb?','Can I take this bag?','Posso levar esta bolsa?'],['knowledge','know how to + base verb','I know how to check in online.','Sei fazer check-in online.'],['transport','by + vehicle','by plane; by bus','de avião; de ônibus']],notes:['Não use to depois de can: can go, não can to go.', 'Luggage é não contável: some luggage, two bags.', 'On foot é a pé; não by foot.']},
        activitySections:[activity('Airport route','Associe cada necessidade ao lugar e dê instruções curtas.',[p('Match','passport · boarding pass · gate · counter → travel document · document to board · boarding place · service desk','passport—travel document; boarding pass—document to board; gate—boarding place; counter—service desk'),p('Complete','Check ___ at counter twelve.','in'),p('Complete','Go to ___ twenty-four.','gate'),p('Complete','The flight is two hours late. It is ___.','delayed'),p('Complete','The flight leaves as planned. It is ___.','on time'),p('Answer','Where do I check in? Counter 12','At counter twelve.'),p('Answer','Where do I board? Gate 24','At gate twenty-four.'),p('Correct','I have two luggages.','I have two bags / some luggage.'),p('Sequence','check in · go through security · go to gate · board','First check in. Then go through security. Go to the gate and board.')],'Airport Map'),activity('Can or can’t?','Forme pedidos, habilidades e possibilidades sem usar to.',[p('Complete','I ___ take this small bag.','can'),p('Complete','You ___ take the large suitcase on the plane.','can’t'),p('Build','I / Can / here / check in / ?', 'Can I check in here?'),p('Build','help / Can / me / you / ?', 'Can you help me?'),p('Make negative','I can drive.','I can’t drive.'),p('Make a question','Sarah can speak Spanish.','Can Sarah speak Spanish?'),p('Answer','Can you drive?','Yes, I can. / No, I can’t.'),p('Answer','Can I take this bag? positive','Yes, you can.'),p('Correct','Can you to help me?','Can you help me?'),p('Correct','I no can find my gate.','I can’t find my gate.')]),activity('Know how and transport','Diga o que sabe fazer e como as pessoas viajaram.',[p('Complete','I know how ___ use the machine.','to'),p('Complete','She doesn’t know how ___ check in online.','to'),p('Transform','I can use the machine.','I know how to use the machine.'),p('Answer','Do you know how to check in online?','Yes, I do. / No, I don’t.'),p('Complete','We traveled ___ plane.','by'),p('Complete','They went ___ foot.','on'),p('Choose','I went (by / on) bus.','by'),p('Choose','I went (by / on) foot.','on'),p('Correct','We traveled with plane.','We traveled by plane.'),p('Create','Say three things you know how to do and one you don’t.','I know how to... I don’t know how to...'),p('Create','Describe how four people arrived at the airport.','... arrived by ...')],'Travel Skills')],
        translations:[t('Posso ver seu passaporte?','Can I see your passport?'),t('Posso levar esta bolsa?','Can I take this bag?'),t('Você não pode levar a mala grande.','You can’t take the large suitcase.'),t('Onde posso fazer check-in?','Where can I check in?'),t('Vá ao portão vinte e quatro.','Go to gate twenty-four.'),t('Meu voo está atrasado.','My flight is delayed.'),t('O voo está no horário.','The flight is on time.'),t('Não sei usar a máquina.','I don’t know how to use the machine.'),t('Viajamos de avião.','We traveled by plane.'),t('Ele foi ao aeroporto de ônibus.','He went to the airport by bus.')],
        expressions:[x('Can I see...?', 'Posso ver...?', 'Pedido frequente no atendimento.','Can I see your boarding pass?','Posso ver seu cartão de embarque?'),x('Can I take...?', 'Posso levar...?', 'Pergunta por permissão.','Can I take this bag?','Posso levar esta bolsa?'),x('Where can I...?', 'Onde posso...?', 'Pede local para uma ação.','Where can I check in?','Onde posso fazer check-in?'),x('Which gate?', 'Qual portão?', 'Confirma local de embarque.','Which gate is it?','Qual é o portão?'),x('Is the flight on time?', 'O voo está no horário?', 'Confirma situação do voo.','Is flight 205 on time?','O voo 205 está no horário?'),x('The flight is delayed.', 'O voo está atrasado.','Atualização de viagem.','The flight is delayed by one hour.','O voo está atrasado em uma hora.'),x('I don’t know how to...', 'Não sei como...', 'Explica dificuldade prática.','I don’t know how to check in.','Não sei fazer check-in.'),x('Could you help me?', 'Poderia me ajudar?', 'Pedido educado como bloco útil.','Could you help me with this machine?','Poderia me ajudar com esta máquina?')],
        dialogues:[
            dialogue('At the check-in desk',line('A','Good morning. Can I see your passport?','Bom dia. Posso ver seu passaporte?'),line('B','Of course. Here it is.','Claro. Aqui está.'),line('A','Where are you flying today?','Para onde você vai viajar hoje?'),line('B','I’m flying to Madrid.','Vou viajar para Madri.'),line('A','Do you have a suitcase to check in?','Você tem uma mala para despachar?'),line('B','Yes. This blue suitcase is mine.','Sim. Esta mala azul é minha.')),
            dialogue('A suitcase on the plane',line('A','Can I take this suitcase on the plane?','Posso levar esta mala no avião?'),line('B','No, it’s too large. You can check it in.','Não, ela é grande demais. Você pode despachá-la.'),line('A','Where can I do that?','Onde posso fazer isso?'),line('B','At the desk next to gate twelve.','No balcão ao lado do portão doze.'),line('A','Thank you for your help.','Obrigado pela ajuda.'),line('B','You’re welcome.','De nada.')),
            dialogue('Finding the gate',line('A','Excuse me. Where can I find gate twenty-four?','Com licença. Onde encontro o portão vinte e quatro?'),line('B','Go straight and turn right after the café.','Siga reto e vire à direita depois do café.'),line('A','Is it far from here?','Fica longe daqui?'),line('B','No. It’s about five minutes from here.','Não. Fica a cerca de cinco minutos daqui.'),line('A','Great. Thank you.','Ótimo. Obrigado.'),line('B','Have a good flight.','Tenha um bom voo.')),
            dialogue('A delayed flight',line('A','Is flight 308 on time?','O voo 308 está no horário?'),line('B','No. It is delayed by forty minutes.','Não. Está atrasado em quarenta minutos.'),line('A','What time can we board?','A que horas podemos embarcar?'),line('B','Boarding starts at nine fifteen.','O embarque começa às nove e quinze.'),line('A','Is the gate still twenty-four?','O portão ainda é o vinte e quatro?'),line('B','Yes. The gate is the same.','Sim. O portão é o mesmo.')),
            dialogue('Using the check-in machine',line('A','Do you know how to use this machine?','Você sabe usar esta máquina?'),line('B','No. Could you help me?','Não. Poderia me ajudar?'),line('A','Sure. First, put your passport here.','Claro. Primeiro, coloque seu passaporte aqui.'),line('B','Okay. What do I do next?','Certo. O que faço depois?'),line('A','Choose your flight on the screen.','Escolha seu voo na tela.'),line('B','Got it. Thank you.','Entendi. Obrigado.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('Daniel’s delayed flight','Daniel arrived at the airport at six thirty. He checked in at counter twelve and put his large suitcase on the belt. He kept a small bag with him. His boarding pass said gate twenty-four, but he couldn’t find it. A worker showed him the way. At the gate, Daniel learned that his flight was delayed by one hour. He called Emma and bought some water. Finally, they boarded at eight fifteen.',question('What time did Daniel arrive?','At six thirty.'),question('Where did he check in?','At counter twelve.'),question('Which bag did he keep?','A small bag.'),question('Could he find the gate?', 'No, he couldn’t.'),question('What happened to the flight?','It was delayed by one hour.'),question('What time did they board?','At eight fifteen.')),
        conversation:{questions:['Name ten airport words.','Explain the route from the entrance to the plane.','Ask permission to take two items.','Say three things you can do when traveling.','Say one thing you don’t know how to do.','Ask for help at a check-in machine.','Ask about a delayed flight.','Describe how you traveled on your last trip.'],support:['Can I...?', 'Where can I...?', 'I can/can’t...', 'I know how to...', 'Which gate?', 'on time/delayed', 'by plane/bus']},
        homework:homework('Prepare um roteiro de aeroporto com documentos, bagagem, portão e um problema.', ['Voo atrasado','Bagagem grande','Máquina de check-in'],['Usei pelo menos quinze palavras de viagem.','Incluí can/can’t e know how to.','Organizei o trajeto e resolvi o problema.']),
        mission:{title:'Get to the gate',task:'Faça check-in, resolva uma restrição de bagagem, encontre o portão e responda a um atraso.',focus:['airport English','can/can’t','practical sequence']}
    }));
    R.get(23).dialogues.push(
        dialogue('Boarding time',line('A','What time can we board?','A que horas podemos embarcar?'),line('B','Boarding starts at eight fifteen.','O embarque começa às oito e quinze.')),
        dialogue('Transport to the airport',line('A','How did you get to the airport?','Como você chegou ao aeroporto?'),line('B','I came by train.','Vim de trem.'))
    );
}());
