(function(){
    'use strict';
    const R=window.A1V3LessonRegistry; const {v,x,p,t,line,dialogue,question,reading,activity,homework}=R.helpers;
    R.register(22,R.lesson({
        title:'What Happened?',
        objectives:['Relatar ações concluídas no passado com verbos regulares e irregulares essenciais.','Formar negativas e perguntas com did.','Organizar uma sequência com yesterday, then, after that e finally.','Distinguir was/were de outros verbos no Past Simple.'],
        intro:[line('Emma','What happened yesterday?','O que aconteceu ontem?'),line('Daniel','I missed the bus, so I walked to work.','Perdi o ônibus, então fui a pé ao trabalho.'),line('Emma','Did you arrive late?','Você chegou atrasado?'),line('Daniel','Yes, I did. I had a meeting at nine, but I arrived at nine fifteen.','Sim. Eu tinha uma reunião às nove, mas cheguei às nove e quinze.'),line('Emma','What did your manager say?','O que seu gerente disse?'),line('Daniel','She smiled and said, “Good morning.”','Ela sorriu e disse: “Bom dia”.')],
        vocab:[v('happen','acontecer','What happened?','O que aconteceu?'),v('miss','perder; não pegar','I missed the bus.','Eu perdi o ônibus.'),v('walk','caminhar','I walked to work.','Fui a pé ao trabalho.'),v('arrive','chegar','We arrived at nine.','Chegamos às nove.'),v('call','ligar','She called me.','Ela me ligou.'),v('visit','visitar','They visited a museum.','Eles visitaram um museu.'),v('stay','ficar','I stayed at home.','Fiquei em casa.'),v('go → went','ir → foi','We went to the beach.','Fomos à praia.'),v('have → had','ter → teve','I had a meeting.','Eu tive uma reunião.'),v('get → got','pegar; chegar; obter → pegou','He got home late.','Ele chegou em casa tarde.'),v('see → saw','ver → viu','I saw Julia.','Eu vi a Julia.'),v('eat → ate','comer → comeu','They ate lunch.','Eles almoçaram.'),v('buy → bought','comprar → comprou','She bought a ticket.','Ela comprou uma passagem.'),v('say → said','dizer → disse','He said hello.','Ele disse olá.'),v('take → took','pegar; levar → pegou','We took a taxi.','Pegamos um táxi.'),v('yesterday','ontem','I worked yesterday.','Trabalhei ontem.'),v('then','então; depois','Then I called Sarah.','Depois liguei para Sarah.'),v('finally','finalmente','Finally, we went home.','Finalmente, fomos para casa.')],
        grammar:{title:'Past Simple',summary:'Use o passado para uma ação concluída. Na negativa e pergunta, did carrega a marca de passado e o verbo volta à forma base.',rows:[['regular','verb + ed','I walked. She visited.','Eu caminhei. Ela visitou.'],['irregular','special past form','go → went; have → had','ir → foi; ter → teve'],['negative','didn’t + base verb','I didn’t walk.','Eu não caminhei.'],['question','Did + subject + base verb?','Did you arrive late?','Você chegou atrasado?'],['short answer','Yes, ... did. / No, ... didn’t.','Yes, I did.','Sim.'],['be','was/were; no did','Were you tired?','Você estava cansado?']],notes:['Regular: work → worked; live → lived; study → studied; stop → stopped.', 'Nunca use did + verbo no passado: Did you go? Não Did you went?', 'Use was/were diretamente: Was she home? Não Did she be home?']},
        activitySections:[activity('Past forms','Produza as formas passadas antes de usá-las na história.',[p('Write the past','work','worked'),p('Write the past','live','lived'),p('Write the past','study','studied'),p('Write the past','stop','stopped'),p('Write the past','go','went'),p('Write the past','have','had'),p('Write the past','see','saw'),p('Write the past','buy','bought'),p('Write the past','take','took'),p('Complete','Yesterday I ___ the bus. (miss)','missed'),p('Complete','We ___ a taxi. (take)','took'),p('Complete','Sarah ___ a ticket. (buy)','bought')],'Verb Forms'),activity('Questions and negatives','Use did/didn’t sem manter o verbo no passado.',[p('Make negative','I walked to work.','I didn’t walk to work.'),p('Make negative','She bought a ticket.','She didn’t buy a ticket.'),p('Make a question','Daniel arrived late.','Did Daniel arrive late?'),p('Make a question','They went home.','Did they go home?'),p('Answer','Did you work yesterday? positive','Yes, I did.'),p('Answer','Did Emma take a taxi? negative','No, she didn’t.'),p('Build','happen / What / did / ?', 'What happened?'),p('Build','you / What / buy / did / ?', 'What did you buy?'),p('Correct','Did you went to work?','Did you go to work?'),p('Correct','I didn’t saw Julia.','I didn’t see Julia.'),p('Choose','(Was / Did) the hotel clean?','Was'),p('Choose','(Was / Did) you visit the museum?','Did')]),activity('Tell the story','Organize eventos e acrescente conectores para formar uma narrativa curta.',[p('Order','finally went home · first missed bus · then took taxi','First, I missed the bus. Then, I took a taxi. Finally, I went home.'),p('Complete','First, we arrived at the hotel. ___, we ate lunch. ___, we visited the beach.','Then; Finally'),p('Retell','7:00 got up · 8:00 missed bus · 8:15 took taxi · 9:15 arrived','I got up at seven. Then I missed the bus. I took a taxi and arrived at nine fifteen.'),p('Answer','What did you do yesterday morning?','I ...'),p('Answer','Where did you go last weekend?','I went to ...'),p('Answer','Who did you see?','I saw ...'),p('Correct','Yesterday I go to the store and buy food.','Yesterday I went to the store and bought food.'),p('Create','Tell a four-event story with one problem.','First... Then... After that... Finally...')],'Story Builder')],
        translations:[t('O que aconteceu ontem?','What happened yesterday?'),t('Eu perdi o ônibus.','I missed the bus.'),t('Fui a pé ao trabalho.','I walked to work.'),t('Você chegou atrasado?','Did you arrive late?'),t('Sim.','Yes, I did.'),t('Eu não peguei um táxi.','I didn’t take a taxi.'),t('O que você comprou?','What did you buy?'),t('Nós fomos à praia.','We went to the beach.'),t('Ela viu a Julia.','She saw Julia.'),t('Finalmente, eles foram para casa.','Finally, they went home.')],
        expressions:[x('What happened?', 'O que aconteceu?', 'Pede um relato do evento.','What happened last night?','O que aconteceu ontem à noite?'),x('Did you...?', 'Você...?', 'Pergunta sobre ação concluída.','Did you call me?','Você me ligou?'),x('Yes, I did. / No, I didn’t.','Sim. / Não.','Resposta curta com did.','Did you go? Yes, I did.','Você foi? Sim.'),x('First,...', 'Primeiro,...','Inicia uma sequência.','First, I called Sarah.','Primeiro, liguei para Sarah.'),x('Then,...', 'Depois,...','Continua a sequência.','Then, we ate lunch.','Depois, almoçamos.'),x('After that,...','Depois disso,...','Liga mais um evento.','After that, we left.','Depois disso, saímos.'),x('Finally,...','Finalmente,...','Fecha a sequência.','Finally, I got home.','Finalmente, cheguei em casa.'),x('I’m sorry I’m late.','Desculpe o atraso.','Pedido de desculpas útil.','I’m sorry I’m late. I missed the bus.','Desculpe o atraso. Perdi o ônibus.')],
        dialogues:[
            dialogue('Late for work',line('A','Why are you late today?','Por que você está atrasado hoje?'),line('B','I missed the bus.','Perdi o ônibus.'),line('A','What did you do?','O que você fez?'),line('B','I called a taxi, but it arrived late.','Chamei um táxi, mas ele chegou tarde.'),line('A','Did you call the office?','Você ligou para o escritório?'),line('B','Yes, I did. I called at eight.','Sim. Liguei às oito.')),
            dialogue('A busy day',line('A','What did you do yesterday?','O que você fez ontem?'),line('B','I worked and visited my parents.','Trabalhei e visitei meus pais.'),line('A','Did you have dinner with them?','Você jantou com eles?'),line('B','Yes. We cooked dinner together.','Sim. Preparamos o jantar juntos.'),line('A','What time did you go home?','Que horas você foi para casa?'),line('B','I went home at ten.','Fui para casa às dez.')),
            dialogue('The train ticket',line('A','Did you buy the train ticket?','Você comprou a passagem de trem?'),line('B','No, I didn’t.','Não.'),line('A','Why not?','Por que não?'),line('B','I forgot my card at home.','Esqueci meu cartão em casa.')),
            dialogue('At home last night',line('A','Were you at home last night?','Você estava em casa ontem à noite?'),line('B','Yes, but I didn’t watch TV.','Sim, mas não assisti TV.'),line('A','What did you do?','O que você fez?'),line('B','I studied English and listened to music.','Estudei inglês e ouvi música.')),
            dialogue('Getting to the hotel',line('A','What happened after the flight?','O que aconteceu depois do voo?'),line('B','We collected our bags and looked for a bus.','Pegamos nossas malas e procuramos um ônibus.'),line('A','Did you find one?','Vocês encontraram um?'),line('B','No, we didn’t. The buses stopped at eleven.','Não. Os ônibus pararam às onze.'),line('A','What happened next?','O que aconteceu depois?'),line('B','We took a taxi and finally arrived at the hotel.','Pegamos um táxi e finalmente chegamos ao hotel.'))
        ],
        dialogueGroups: [[0, 1], [2, 3, 4]],
        reading:reading('A difficult morning','Yesterday, Emma got up at seven and made breakfast. She left home at eight, but she missed her bus. She called Daniel and then walked to the station. Daniel arrived in his car and took her to work. They stopped for coffee, so Emma arrived at nine fifteen. Her meeting was at nine, but her manager didn’t get angry. She smiled and gave Emma a cup of coffee.',question('What time did Emma get up?','At seven.'),question('Why did she walk to the station?','She missed her bus.'),question('Who took her to work?','Daniel did.'),question('Did they stop for coffee?','Yes, they did.'),question('Was her manager angry?','No, she wasn’t.'),question('What did the manager give her?','A cup of coffee.')),
        conversation:{questions:['Say five regular past forms.','Say eight irregular past forms.','Tell what you did yesterday morning.','Ask five questions with did.','Answer with full sentences.','Tell one thing you didn’t do.','Retell a difficult day in chronological order.','Change one event and tell the story again.'],support:['Yesterday,...','What happened?','Did you...?', 'I didn’t...', 'First...', 'Then...', 'After that...', 'Finally...']},
        homework:homework('Escreva e prepare oralmente uma história com oito eventos concluídos.',['Uma manhã difícil','Um passeio','Um dia de sorte'],['Usei verbos regulares e irregulares.','Incluí duas negativas e três perguntas.','Organizei os eventos com conectores.']),
        mission:{title:'Reconstruct yesterday',task:'Reconstrua um dia a partir de horários e pistas, responda a perguntas e corrija uma informação falsa.',focus:['Past Simple','did/didn’t','story sequence']}
    }));
}());
