// Historical first-pass migration; later editorial revisions live in lesson-data.
// Never run this over the current lessons: homework and conversation tasks were revised manually.
if (!process.argv.includes("--restore-initial-draft")) throw Error("Historical utility: current source of truth is a1-v3/lesson-data/.");
const fs=require('fs');
const archive=JSON.parse(fs.readFileSync('docs/archive/a1-v3-32-content.json','utf8'));
const plan=JSON.parse(fs.readFileSync('docs/archive/a1-v3-38-plan.json','utf8'));
global.window={};require('../js/v3-curriculum.js');require('../a1-v3/a1-v3-lesson-registry.js');
for(const slug of ['at-the-cafe','my-everyday-life','a-day-in-my-life'])require('../a1-v3/lesson-data/preview-'+slug+'.js');
const sourceMap={1:1,2:4,4:2,5:6,10:9,11:11,13:12,14:13,16:14,17:16,19:17,20:18,22:19,25:21,26:22,28:23,31:26,32:27,34:28,35:29};
const clean=text=>String(text||'').replace(/(?:na|da|a partir da) [Ll]ição \d+/g,'neste percurso');
const verbs={
 be:['ser; estar','was / were · been'],work:['trabalhar','worked · worked'],spell:['soletrar','spelled · spelled'],repeat:['repetir','repeated · repeated'],say:['dizer','said · said'],write:['escrever','wrote · written'],live:['morar; viver','lived · lived'],study:['estudar','studied · studied'],start:['começar','started · started'],finish:['terminar','finished · finished'],go:['ir','went · gone'],have:['ter','had · had'],love:['amar','loved · loved'],visit:['visitar','visited · visited'],sit:['sentar-se','sat · sat'],put:['colocar','put · put'],look:['olhar','looked · looked'],need:['precisar','needed · needed'],buy:['comprar','bought · bought'],eat:['comer','ate · eaten'],drink:['beber','drank · drunk'],pay:['pagar','paid · paid'],cost:['custar','cost · cost'],choose:['escolher','chose · chosen'],prefer:['preferir','preferred · preferred'],wear:['vestir; usar','wore · worn'],belong:['pertencer','belonged · belonged'],find:['encontrar','found · found'],lose:['perder','lost · lost'],carry:['carregar','carried · carried'],wait:['esperar','waited · waited'],talk:['conversar','talked · talked'],send:['enviar','sent · sent'],turn:['virar','turned · turned'],stop:['parar','stopped · stopped'],walk:['caminhar','walked · walked'],travel:['viajar','traveled · traveled'],stay:['ficar; hospedar-se','stayed · stayed'],arrive:['chegar','arrived · arrived'],see:['ver','saw · seen'],take:['pegar; levar','took · taken'],leave:['sair; deixar','left · left'],board:['embarcar','boarded · boarded'],call:['ligar; chamar','called · called'],invite:['convidar','invited · invited'],bring:['trazer','brought · brought'],feel:['sentir-se','felt · felt'],rest:['descansar','rested · rested'],help:['ajudar','helped · helped'],hurt:['doer; machucar','hurt · hurt'],speak:['falar','spoke · spoken'],answer:['responder','answered · answered'],relax:['relaxar','relaxed · relaxed']
};
const verbSelection={1:['be'],2:['be','spell','repeat','say'],4:['be','work'],5:['say','spell','repeat','write'],10:['live','work','study','go','have'],11:['have','live','love','visit'],13:['have','sit','put','look'],14:['need','buy','have','eat','drink'],16:['buy','pay','cost','choose'],17:['wear','prefer','choose','buy'],19:['belong','find','lose','have'],20:['carry','wait','talk','send','wear'],22:['be','have','wear','look'],23:['go','turn','stop','walk'],25:['be','travel','stay'],26:['go','have','see','visit','stay'],28:['travel','take','leave','board'],29:['wait','board','leave','call'],31:['invite','bring','go','stay'],32:['have','feel','rest','help','call'],34:['call','answer','speak','leave','repeat'],35:['start','finish','rest','relax','go']};
const verbExamples={be:'I am here.',work:'I work at a school.',spell:'Can you spell your name?',repeat:'Please repeat your name.',say:'Say your name, please.',write:'I write my name here.',live:'She lives near the school.',study:'He studies English.',start:'She starts work at eight.',finish:'I finish work at five.',go:'We go home at six.',have:'She has two brothers.',love:'I love my family.',visit:'We visit our grandparents.',sit:'I sit on this chair.',put:'Put the book on the desk.',look:'Look at the room.',need:'We need some milk.',buy:'I buy bread here.',eat:'I eat rice for lunch.',drink:'I drink water.',pay:'Can I pay by card?',cost:'It costs ten dollars.',choose:'Choose a color.',prefer:'I prefer the blue one.',wear:'I wear a blue shirt.',belong:'It belongs to Mia.',find:'I can find my bag.',lose:'I sometimes lose my keys.',carry:'She is carrying a bag.',wait:'We are waiting here.',talk:'They are talking.',send:'I am sending a message.',turn:'Turn left here.',stop:'Stop at the park.',walk:'I walk to the station.',travel:'I travel by bus.',stay:'We stayed at a hotel.',arrive:'We arrived at nine.',see:'I saw my friend.',take:'I took the bus.',leave:'The plane leaves at ten.',board:'We board at gate four.',call:'I will call you.',invite:'I am going to invite Sam.',bring:'Bring a jacket.',feel:'I feel tired.',rest:'I need to rest.',help:'Can you help me?',hurt:'My head hurts.',speak:'Can I speak to Mia?',answer:'I answer the phone.',relax:'I relax after work.'};
const slide=(id,type,title,instruction,extra={})=>({id,type,title,kicker:type==='conversation'?'Conversation Activities':type==='patterns'?'Helping You':title,instruction,...extra});
const task=(id,title,instruction,tasks,goal,challenge)=>slide(id,'conversation',title,instruction,{tasks,goal,challenge});
const mission=(id,title,instruction,board,steps,support,model,surprise)=>slide(id,'mission',title,instruction,{board,steps,support,model,...(surprise?{surprise}:{})});
function homework(row){return slide('homework','homework','Take it with you.','Escolha uma opção para praticar antes do próximo encontro.',{options:[['A','Speak','Prepare um áudio de 30–60 segundos: '+row.outcome],['B','Write','Escreva uma mensagem ou diálogo curto: '+row.outcome],['C','Make a card','Crie um cartão com palavras-chave e prepare uma apresentação oral: '+row.outcome]]});}
function exit(row){return slide('exit','exit','Look at your progress.','Diga o que conseguiu fazer e escolha um ponto para retomar.',{checks:[row.outcome,'Consegui pedir repetição ou esclarecimento.','Consigo tentar novamente com menos apoio.']});}
function base(row){return {title:row.title,type:row.kind==='lexical'?'content':'review',summary:row.outcome,mission:{title:row.title,task:row.outcome,focus:[row.focus],semanticTags:window.V3Curriculum.getLesson('a1-v3',row.number).languageTags},slides:[]};}
function convert(row,n){const o=archive.lessons[n-1],l=base(row);const d=l.slides;
 d.push(slide('opening','dialogue',row.title,'Acompanhe a leitura do professor. Depois leiam juntos e identifiquem a situação.',{lines:o.intro}));
 d.push(slide('vocabulary','cards','Vocabulary Expansion','Leia os significados e exemplos. Escolha palavras para usar durante a conversa.',{cards:o.vocab.map(([w,m,e])=>[w,m,e])}));
 d.push(slide('verbs','verbs','Verb bank','Consulte o infinitivo, o passado e o particípio. Observe nos exemplos a forma usada na frase.',{cards:verbSelection[row.number].map(v=>[v,verbs[v][0],verbExamples[v],verbs[v][1]])}));
 d.push(slide('helping','patterns','Helping You',clean(o.grammar.summary),{groups:[{title:clean(o.grammar.title),cards:o.grammar.rows.map(([label,pattern,example,translation])=>[pattern,translation||label,example])},{title:'Como usar',cards:o.grammar.notes.map((note,i)=>['Observe '+(i+1),clean(note),''])}]}));
 for(const [i,section] of o.activitySections.entries())d.push(slide('practice-'+i,'drill',section.title,clean(section.instruction),{items:section.items.map(x=>[x[1],x[3]])}));
 if(o.translations.length)d.push(slide('drill','drill','Say it in English.','Diga a frase em inglês. Confira o modelo e depois personalize uma informação.',{items:o.translations}));
 d.push(slide('expressions','cards','Key phrases & expressions','Use cada expressão como um bloco. Leia o exemplo e crie uma troca curta.',{cards:o.expressions.map(([w,m,n,e])=>[w,m+' · '+n,e])}));
 const lines=[],lineTitles={};for(const g of o.dialogues){lineTitles[lines.length]=g.title;lines.push(...g.lines);}d.push(slide('dialogues','dialogue','Dialog Samples','Leiam as situações e troquem os papéis. Depois alterem uma informação.',{lines,lineTitles}));
 if(o.reading.text)d.push(slide('reading','reading',o.reading.title,'O professor lê primeiro. Depois leia e responda às perguntas consultando o texto.',{paragraphs:o.reading.text.split(/\n+/).filter(Boolean),items:o.reading.questions}));
 for(const [i,extra] of (o.afterVocabularySlides||[]).entries())d.splice(2+i,0,slide('reference-'+i,'reference',extra.title,'Consulte estes exemplos durante a prática.',{body:extra.body||extra.content}));
 const prompts=o.conversation.questions.length?o.conversation.questions.slice(0,6):o.objectives.map(x=>clean(x));
 d.push(task('talk',"Let's Talk",'Converse com o professor usando suas informações ou um perfil inventado.',prompts.map((q,i)=>['Pergunta '+(i+1),q]),row.outcome,'Depois de responder, faça uma pergunta ao professor.'));
 d.push(exit(row),homework(row));return l;
}
// Fully authored new town lesson and current-travel lesson; past continuous is an optional reference only.
function authorLexical(row,vocab,lines,patterns,expressions,drills,paragraphs,questions,board,steps,support,model){const l=base(row);l.slides=[slide('opening','dialogue',row.title,'Acompanhe a primeira leitura e depois leia com o professor.',{lines}),slide('vocabulary','cards','Vocabulary Expansion','Leia cada palavra com seu exemplo e use-a para explicar a situação.',{cards:vocab}),slide('verbs','verbs','Verb bank','Consulte as três formas; pratique os exemplos em contexto.',{cards:verbSelection[row.number].map(v=>[v,verbs[v][0],verbExamples[v],verbs[v][1]])}),slide('helping','patterns','Helping You','Compare os modelos e observe como perguntar e responder.',{cards:patterns}),slide('drill','drill','Say it in English.','Responda oralmente, confira e tente novamente.',{items:drills}),slide('expressions','cards','Key phrases & expressions','Leia o bloco inteiro e faça uma troca com o professor.',{cards:expressions}),slide('dialogues','dialogue','Dialog Samples','Troquem os papéis e adaptem o destino ou horário.',{lines}),slide('reading','reading','A useful message','Leia a mensagem e encontre as informações necessárias.',{paragraphs,items:questions}),mission('talk',"Let's Talk",row.outcome,board,steps,support,model),exit(row),homework(row)];return l;}
const word=(w,m,e)=>[w,m,e];
function town(row){return authorLexical(row,[word('station','estação','The station is near the park.'),word('bus stop','ponto de ônibus','Wait at the bus stop.'),word('bank','banco','The bank is on the left.'),word('pharmacy','farmácia','The pharmacy is next to the bank.'),word('supermarket','supermercado','Go to the supermarket.'),word('park','parque','Meet me at the park.'),word('museum','museu','The museum is on Green Street.'),word('library','biblioteca','The library is near here.'),word('café','cafeteria','The café is across from the park.'),word('corner','esquina','Turn at the corner.'),word('traffic lights','semáforo','Stop at the traffic lights.'),word('left','esquerda','Turn left.'),word('right','direita','Turn right.'),word('straight ahead','em frente','Go straight ahead.'),word('near','perto','It is near the station.'),word('far','longe','It is far from here.'),word('on foot','a pé','I go on foot.'),word('by bus','de ônibus','We go by bus.'),word('by train','de trem','I travel by train.'),word('tonight','hoje à noite','We go out tonight.')],
 [['A','Excuse me. Where is the station?','Com licença. Onde fica a estação?'],['B','It is near the park.','Fica perto do parque.'],['A','Can you help me?','Pode me ajudar?'],['B','Yes. Go straight ahead and turn left.','Sim. Siga em frente e vire à esquerda.'],['A','At the traffic lights?','No semáforo?'],['B','Yes. The station is on your right.','Sim. A estação fica à sua direita.'],['A','Thank you. Can I go on foot?','Obrigado. Posso ir a pé?'],['B','Yes. It is near here.','Sim. Fica perto daqui.']],
 [['Where is…?','Pergunte a localização de um lugar.','Where is the bank?'],['Can you help me?','Use can para pedir ajuda. Depois de can, use o verbo sem to.','Can you repeat, please?'],['I can / I can’t','Diga o que consegue fazer.','I can walk there. I can’t drive.'],['Go / Turn / Stop','Comece a orientação com o verbo.','Go straight ahead. Turn right.'],['by bus / on foot','Use estas combinações para o transporte.','I go by bus. She goes on foot.']],
 [['Excuse me.','Com licença.','Excuse me. Where is the library?'],['Can you help me?','Pode me ajudar?','Can you help me find the bank?'],['Go straight ahead.','Siga em frente.','Go straight ahead to the park.'],['Turn left.','Vire à esquerda.','Turn left at the corner.'],['Turn right.','Vire à direita.','Turn right at the bank.'],['On your left.','À sua esquerda.','The café is on your left.'],['Near here.','Perto daqui.','It is near here.'],['How about the park?','Que tal o parque?','How about the park tonight?'],['Let’s go out.','Vamos sair.','Let’s go out tonight.'],['Is that right?','Está certo?','Turn left. Is that right?']],
 [['Onde fica a estação?','Where is the station?'],['Pode me ajudar?','Can you help me?'],['Siga em frente.','Go straight ahead.'],['Vire à esquerda no banco.','Turn left at the bank.'],['A farmácia fica à sua direita.','The pharmacy is on your right.'],['Eu vou a pé.','I go on foot.'],['Nós vamos de ônibus.','We go by bus.'],['Eu não sei dirigir.','I can’t drive.'],['Pode repetir?','Can you repeat, please?'],['Vamos sair hoje à noite.','Let’s go out tonight.']],
 ['Hi Jo! Meet me at the café tonight at six. The café is next to the library on Green Street. From the station, go straight ahead and turn right at the park. The café is on your left. You can go on foot.'],[['Where is the café?','It is next to the library on Green Street.'],['What time is the meeting?','At six.'],['Where do you turn right?','At the park.'],['Can you go on foot?','Yes, you can.']], [['Route','Station → straight ahead → park → turn right → café on the left'],['Alternative','Station → turn left → bank on the right']],['Peça orientação até o café.','Confirme os passos.','Troquem os papéis e expliquem como chegar ao banco.'],['Where is…?','Can you…?','Go…','Turn…'],'A: Where is the café? B: Go straight ahead and turn right at the park. A: On my left? B: Yes.');}
function updates(row){const l=authorLexical(row,[word('gate','portão','Go to gate seven.'),word('flight','voo','Our flight is late.'),word('screen','tela','Look at the screen.'),word('announcement','anúncio','Listen to the announcement.'),word('delay','atraso','There is a delay.'),word('delayed','atrasado','The flight is delayed.'),word('ready','pronto','We are ready.'),word('early','cedo','We are early.'),word('late','atrasado','He is late.'),word('on time','no horário','The bus is on time.'),word('waiting','esperando','We are waiting.'),word('boarding','embarcando','They are boarding.'),word('leaving','saindo','The plane is leaving.'),word('calling','ligando; chamando','She is calling Ben.'),word('new','novo','Check the new gate.'),word('change','mudança','There is a gate change.'),word('departure','partida','Departure is at ten.'),word('arrival','chegada','Arrival is at twelve.'),word('now','agora','We are boarding now.'),word('message','mensagem','Send a message.')],
 [['A','Are you boarding now?','Você está embarcando agora?'],['B','No. We are waiting at gate two.','Não. Estamos esperando no portão dois.'],['A','Look at the screen. The gate is different.','Olhe a tela. O portão é diferente.'],['B','What is the new gate?','Qual é o novo portão?'],['A','Gate seven. Departure is at ten thirty.','Portão sete. A partida é às dez e meia.'],['B','Is the flight late?','O voo está atrasado?'],['A','Yes. I am calling Ben now.','Sim. Estou ligando para Ben agora.'],['B','Tell him: gate seven, ten thirty.','Diga a ele: portão sete, dez e meia.']],
 [['am/is/are + -ing','Descreva uma ação acontecendo agora.','We are waiting at the airport.'],['Are you…? / Is she…?','Coloque are ou is antes da pessoa na pergunta.','Are you boarding? No, I’m not.'],['is late / is delayed','Para a condição do voo, use be + adjetivo.','The flight is delayed.'],['new gate / new time','Confirme os dois detalhes antes de avisar outra pessoa.','Gate seven. At ten thirty.']],
 [['Look at the screen.','Olhe a tela.','Look at the screen for the gate.'],['What is the new gate?','Qual é o novo portão?','What is the new gate for our flight?'],['The flight is delayed.','O voo está atrasado.','The flight is delayed today.'],['We are waiting.','Estamos esperando.','We are waiting near the café.'],['Are you ready?','Você está pronto?','Are you ready to go?'],['Not yet.','Ainda não.','Are you boarding? Not yet.'],['Right now.','Agora mesmo.','I am calling her right now.'],['On time.','No horário.','The flight is on time.'],['Let me check.','Deixe-me conferir.','Let me check the new time.'],['See you there.','Vejo você lá.','Gate seven. See you there.']],
 [['Estamos esperando.','We are waiting.'],['Ela está ligando para Ben.','She is calling Ben.'],['Eles estão embarcando?','Are they boarding?'],['Não estou embarcando.','I am not boarding.'],['O voo está atrasado.','The flight is delayed.'],['Qual é o novo portão?','What is the new gate?'],['Olhe a tela.','Look at the screen.'],['A partida é às dez e meia.','Departure is at ten thirty.'],['Você está pronto?','Are you ready?'],['Estamos no portão sete.','We are at gate seven.']],
 ['Hi Ben. We are waiting at the airport. Our flight is delayed. The old gate is two, but the new gate is seven. Departure is at ten thirty, not ten. Mia is getting water and I am checking the screen. See you at gate seven.'],[['Are they boarding?','No. They are waiting.'],['What is the new gate?','Gate seven.'],['What time is departure?','At ten thirty.'],['What is Mia doing?','She is getting water.']], [['Original','Gate 2 · departure 10:00'],['Update','Gate 7 · departure 10:30'],['People','Ben: at the café · Mia: getting water']],['Avise Ben sobre a mudança.','Pergunte onde Mia está e o que faz.','Confirme portão e horário.'],['We are…','The new gate is…','At…','Where is…?'],'Ben, the flight is delayed. We are waiting at gate seven. Departure is at ten thirty.');l.slides.splice(l.slides.length-2,0,slide('extension','patterns','Extra · a moment yesterday','Extensão opcional. Compare agora com um momento do passado.',{cards:[['was / were + -ing','Para uma ação em andamento em um momento passado, troque am/is/are por was/were.','Now: I am waiting. Yesterday at ten: I was waiting.'],['Were you waiting?','Responda usando was ou were.','Yes, I was. / No, I wasn’t.']]}));return l;}
// One communicative cycle = a different real-world outcome; no grammar drills in CA.
const ca={
3:{scene:'A welcome desk',cards:[['Ana','first name: Ana · last name: Silva · nickname: Ana'],['Leo','first name: Leonardo · last name: Costa · nickname: Leo'],['Mia','first name: Mia · last name: Green · nickname: Mia']],questions:['What’s your name?','How do you spell your last name?','What’s your nickname?'],message:'Hello! I’m Mia Green. My nickname is Mia. This is Leo. His last name is Costa.',checks:[['What is Mia’s last name?','Green.'],['What is his nickname?','Leo.']],twist:'O professor soletra uma letra errada. Peça repetição e confirme o sobrenome.',finish:'Apresente a si e a outra pessoa, soletrando os sobrenomes.'},
6:{scene:'A registration desk',cards:[['Visitor 1','Ana Costa · nurse · 42 Green Street · 555-2184 · ana@example.com'],['Visitor 2','Leo Silva · teacher · 71 Park Avenue · 555-8132 · leo@example.com'],['Form','Name / Job / Address / Phone / Email']],questions:['What do you do?','What’s your address?','What’s your phone number?'],message:'My name is Leo Silva. I am a teacher. My phone number is 555-8132. My email is leo@example.com.',checks:[['What does Leo do?','He is a teacher.'],['What is his phone number?','555-8132.']],twist:'O cadastro mostra 555-8123. Confira e corrija o telefone.',finish:'Complete um cadastro fictício com nome, profissão e contato. Depois confirme os dados.'},
12:{scene:'People behind the names',cards:[['Rita','Mia’s mother · teacher · starts at 8:00 · lives in Recife'],['Dan','Mia’s brother · student · studies at night · lives in Recife'],['Mia','Dan’s sister · nurse · works at night · lives in Olinda']],questions:['Who is Rita?','Where does Dan live?','Does Mia work at night?'],message:'Rita is my mother. She is a teacher and starts work at eight. Dan is my brother. He studies at night. We live in Recife, but my sister Mia lives in Olinda.',checks:[['Who is Rita?','She is the speaker’s mother.'],['Where does Mia live?','She lives in Olinda.']],twist:'Dan agora estuda de manhã. Atualize o perfil sem mudar os outros dados.',finish:'Entreviste o professor sobre uma pessoa e apresente três informações e uma relação familiar.'},
15:{scene:'Lunch is almost ready',cards:[['Kitchen','On the table: two plates, one glass · In the fridge: eggs, cheese, milk'],['Living room','Under the chair: a bag with bread · On the desk: two bottles of water'],['Shopping','For lunch: bread, cheese, water, tomatoes · We have no tomatoes']],questions:['Where is the bread?','Do we have any cheese?','How many bottles of water are there?'],message:'The bread is in the bag under the chair. We have some cheese and two bottles of water. There aren’t any tomatoes. Please put the plates on the table.',checks:[['Where is the bag?','Under the chair.'],['What do we need to buy?','Tomatoes.']],twist:'Agora há quatro pessoas para o almoço. Decidam o que mais precisam.',finish:'Localize os itens, confirme o que há e faça uma lista de compras curta.'},
18:{scene:'One item, two choices',cards:[['Blue T-shirt','Size M · $18 · available'],['Red T-shirt','Size M · $15 · sold out'],['Green T-shirt','Size L · $20 · available'],['Customer','You want size M. You have $20.']],questions:['How much is the blue one?','Do you have it in size M?','Can I pay by card?'],message:'Hello. I want a T-shirt in size M. I like red, but the red one is not available. The blue one is eighteen dollars. I have twenty dollars.',checks:[['Which color is unavailable?','Red.'],['Which shirt can the customer buy?','The blue T-shirt.']],twist:'A loja só aceita dinheiro. Você tem $15 em dinheiro. Combine outra forma de resolver a compra.',finish:'Escolha uma peça, pergunte preço e tamanho e confirme como pagar.'},
21:{scene:'Whose bag is it?',cards:[['Mia','Red bag · wearing glasses · waiting near the door'],['Ben','Blue bag · wearing a green shirt · talking on the phone'],['Ana','Black bag · wearing a white shirt · sitting by the window']],questions:['Whose bag is this?','Is it hers?','What is Ben doing?'],message:'There is a red bag on the chair. A woman with glasses is waiting near the door. She says, “That bag is mine. Thank you!” Ben is talking on the phone. His bag is blue.',checks:[['Who owns the red bag?','Mia.'],['What is Ben doing?','He is talking on the phone.']],twist:'O professor entrega a bolsa azul à pessoa errada. Explique de quem é.',finish:'Identifique o dono por perguntas, descreva o que ele está fazendo e devolva o objeto.'},
24:{scene:'Meet me near the park',cards:[['Your friend','Jo · short dark hair · blue jacket · friendly'],['Meeting','6:00 · café next to the library'],['Route','Station → straight ahead → park → right → café on the left']],questions:['What does Jo look like?','Where is the café?','Can I go on foot?'],message:'Jo is waiting at the café next to the library. Jo has short dark hair and is wearing a blue jacket. From the station, go straight ahead and turn right at the park. Meet at six.',checks:[['What is Jo wearing?','A blue jacket.'],['Where do you turn right?','At the park.']],twist:'Jo está agora em frente à biblioteca. Atualize a orientação.',finish:'Descreva quem encontrar, combine o horário e explique o caminho.'},
27:{scene:'Three moments from a trip',cards:[['Friday','Arrived in Salvador · stayed at a hotel'],['Saturday','Visited a museum · had lunch by the beach'],['Sunday','Saw a friend · went home by bus']],questions:['Where were you on Friday?','What did you do on Saturday?','Did you see a friend?'],message:'Last weekend I was in Salvador. I arrived on Friday and stayed at a hotel. On Saturday I visited a museum. On Sunday I saw a friend and went home by bus.',checks:[['Where did the person stay?','At a hotel.'],['When did the person see a friend?','On Sunday.']],twist:'A viagem terminou na segunda-feira. Acrescente um acontecimento de domingo à noite.',finish:'Conte três acontecimentos em ordem e entreviste o professor sobre uma viagem.'},
30:{scene:'The gate has changed',cards:[['Original plan','Flight 218 · gate 3 · departure 9:00'],['New screen','Flight 218 · gate 8 · departure 10:30'],['Your friend','At the café near gate 3 · waiting for you']],questions:['What is the new gate?','What time is departure?','Where are you waiting?'],message:'Our flight is delayed. Departure is at ten thirty and the new gate is eight. I am waiting at the café near gate three. Please call me when you are ready.',checks:[['What time is departure now?','At ten thirty.'],['Where is the friend?','At the café near gate three.']],twist:'O amigo não ouviu o número do portão. Repita e confirme sem recomeçar toda a conversa.',finish:'Avise sobre a mudança, combinem onde se encontrar e confirmem os detalhes.'},
33:{scene:'Can we meet another day?',cards:[['First plan','Saturday · park · 3:00'],['Problem','Rainy weather · you feel tired and need to rest'],['Alternatives','Sunday at 4:00 · Monday at 6:00']],questions:['How do you feel?','Are you going to stay home?','How about Sunday at four?'],message:'Hi! I feel tired today and I need to rest. I am not going to the park. Can we meet on Sunday at four? I will call you tomorrow.',checks:[['Why is the person staying home?','The person feels tired and needs to rest.'],['What is the new suggestion?','Sunday at four.']],twist:'O professor não pode no domingo. Escolham a outra data e confirmem.',finish:'Explique uma necessidade, recuse o plano com educação e combine outra data.'},
36:{scene:'A message about next week',cards:[['Old schedule','Tuesday · English at 6:00 · work until 5:00'],['New schedule','Tuesday · work until 7:00 · free on Wednesday at 6:00'],['Call','Teacher unavailable · leave name, reason and callback time']],questions:['Can I speak to the teacher?','Can I leave a message?','Can we meet on Wednesday?'],message:'This is Ana. I work until seven on Tuesday, so I need to change my English class. I am free on Wednesday at six. Please call me after five. Thank you.',checks:[['Why does Ana need to change the class?','She works until seven on Tuesday.'],['When can the teacher call?','After five.']],twist:'A pessoa que atende anotou Thursday. Corrija o dia e repita o horário.',finish:'Deixe uma mensagem e escreva uma confirmação curta do novo compromisso.'}
};
function conversation(row,c){const l=base(row);l.slides=[task('opening',c.scene,'Observe as pistas. Diga o que entende e escolha por onde começar.',c.cards,'Your mission',c.finish),task('detective','Ask to discover.','O professor escolhe uma das opções sem dizer qual. Use perguntas para descobrir.',c.cards,'Find and confirm.',c.questions.join(' / ')),slide('reading','reading','A message to work with','O professor lê a mensagem; depois leia e responda. Use as informações na próxima tarefa.',{paragraphs:[c.message],items:c.checks}),task('interview','Now it is about you.','Responda com dados reais ou inventados. Depois faça as perguntas ao professor.',c.questions.map((q,i)=>['Pergunta '+(i+1),q]),'Find one new detail.','Faça uma pergunta de acompanhamento e conte o que descobriu.'),mission('solve','Make it happen.',c.finish,c.cards,['Inicie a conversa.','Descubra e confirme as informações.','Cheguem a uma solução.'],c.questions,c.message,c.twist),task('repair','Something changes.','Retomem a conversa e resolvam esta mudança.',[['Nova situação',c.twist]],'Confirm the new result.','Troquem quem pergunta e quem responde. Não é preciso repetir todas as falas anteriores.'),task('final','Your turn, without a script.','Inventem novos nomes e detalhes para a mesma situação.',[['Objetivo',c.finish],['Apoio opcional',c.questions.join(' / ')]],'Complete the conversation.', 'Na segunda tentativa, use menos apoio e acrescente uma pergunta.'),exit(row),homework(row)];return l;}
function consolidate(row){const selections=row.number===37?[6,12,15,18]:[21,24,30,36];const l=base(row);l.slides=[task('opening',row.title,'Escolha duas situações para começar. As outras serão retomadas depois.',selections.map(n=>[plan[n-1].title,plan[n-1].outcome]),'Show what you can do.','Use informações novas. O professor pode oferecer uma pista quando necessário.')];for(const n of selections){const c=ca[n];l.slides.push(mission('station-'+n,c.scene,c.finish,c.cards,['Converse e reúna as informações.','Resolva a tarefa.','Confira os detalhes e a clareza da mensagem.'],c.questions,c.message,c.twist));}l.slides.push(task('portfolio','A message worth keeping.','Escolha uma situação resolvida e transforme a conversa em uma mensagem curta.',[['Inclua','Nome ou destinatário · informação principal · confirmação'],['Releia','Está claro quem, onde e quando?']],'Read your message aloud.','O professor responde à mensagem. Corrija algo que não ficou claro.'),task('retry','Try it once more.','Escolha a tarefa que exigiu mais apoio.',[['Mude','Uma pessoa, um lugar ou um horário'],['Mantenha','O objetivo da conversa']],'Use less help this time.','Explique o que ficou mais fácil e escolha dois pontos para continuar praticando.'),exit(row),homework(row));return l;}
const lessons=plan.map(row=>{if(row.number===7||row.number===8||row.number===9){const key={7:'cafe',8:'routine',9:'day'}[row.number],src=window.A1V3LessonRegistry.getPreview('a1-preview-'+key);return {...base(row),slides:JSON.parse(JSON.stringify(src.slides))};}if(row.number===23)return town(row);if(row.number===29)return updates(row);if(row.kind==='consolidation')return consolidate(row);if(row.kind==='communicative')return conversation(row,ca[row.number]);return convert(row,sourceMap[row.number]);});
// Keep A1 health focused on expressing needs and practical help, not giving medical advice.
const health=lessons[31];health.slides=health.slides.filter(s=>!['practice-0','practice-1','drill','helping','dialogues','reading','talk'].includes(s.id));health.slides.find(s=>s.id==='opening').lines=[['A','Are you OK?','Você está bem?'],['B','I feel tired and I have a headache.','Estou cansado e com dor de cabeça.'],['A','Do you need help?','Precisa de ajuda?'],['B','Yes. I need to call home.','Sim. Preciso ligar para casa.'],['A','I’ll get your phone.','Vou pegar seu telefone.'],['B','Thank you. I need to rest.','Obrigado. Preciso descansar.']];health.slides=health.slides.filter(s=>s.id!=='expressions');health.slides.splice(3,0,slide('helping','patterns','Helping You','Diga como se sente e peça ajuda prática.',{cards:[['I have…','Use have com um sintoma.','I have a headache.'],['I feel…','Use feel com tired, sick ou dizzy.','I feel tired.'],['I need… / I need to…','Diga de que precisa ou o que precisa fazer.','I need water. I need to rest.'],['I’ll…','Ofereça uma ação simples.','I’ll call your family.']]}),slide('drill','drill','Say what you need.','Diga a frase em inglês.',{items:[['Estou cansado.','I feel tired.'],['Estou com dor de cabeça.','I have a headache.'],['Preciso de água.','I need water.'],['Preciso descansar.','I need to rest.'],['Pode me ajudar?','Can you help me?'],['Vou ligar para sua família.','I’ll call your family.']]}),slide('expressions','cards','Key phrases & expressions','Use estes blocos para pedir e oferecer ajuda.',{cards:[['Are you OK?','Você está bem?','Are you OK today?'],['What’s wrong?','O que houve?','What’s wrong? I feel sick.'],['I feel tired.','Estou cansado.','I feel tired today.'],['I need some water.','Preciso de água.','I need some water, please.'],['Can you help me?','Pode me ajudar?','Can you help me call home?'],['I need to rest.','Preciso descansar.','I need to rest now.'],['I’ll call home.','Vou ligar para casa.','I’ll call home for you.'],['Thank you for your help.','Obrigado pela ajuda.','Thank you for your help today.']]}),slide('reading','reading','A message home','Leia e encontre o pedido de ajuda.',{paragraphs:['Hi Sam. I feel tired and I have a headache. I need to rest. Can you call me? My phone is in my bag. Thank you.'],items:[['How does the person feel?','Tired.'],['What does the person need?','To rest.'],['Where is the phone?','In the bag.']]}),task('talk','Ask for help.','Um pede ajuda prática; o outro oferece uma ação.',[['Situação','Você precisa descansar e ligar para casa.'],['Apoio','I feel… / I need… / Can you…? / I’ll…']],'Confirm the help you need.','Troquem os papéis e mudem o pedido.'));
// Correct early scaffolding and keep reference material from being a production requirement.
for(const l of lessons){for(const s of l.slides){if(s.type==='reading'&&!s.translations)s.translations=[];}const row=plan.find(r=>r.title===l.title);l.migration={sourceLesson:sourceMap[row.number]?archive.manifest[sourceMap[row.number]-1].id:null,editorialVersion:'2026.09-a1-38'};fs.writeFileSync('a1-v3/lesson-data/licao-'+String(row.number).padStart(2,'0')+'.js',"(function(){'use strict';window.A1V3LessonRegistry.register("+row.number+','+JSON.stringify(l,null,2)+");}());\n");}
console.log('Authored 38 individual lessons:',lessons.reduce((n,l)=>n+l.slides.length,0),'sections');
